In [4]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent

import pandas as pd

pd.set_option('display.max_columns', None)  # none은 제한값 자리(몇개 열까지 보여줄까)
pd.set_option('display.max_rows', None)

# ============================================================
# 0. 데이터 불러오기
# ============================================================

train = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / 'train_split.parquet')
val = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / 'val_split.parquet')

In [5]:
# ============================================================
# 1. 수위 차분 파생변수 생성
# ============================================================
# wl_diff_00h = wl_t(현재수위) - wl_t_minus_00h 파생변수 5개 생성

train_fe = train.copy()
val_fe = val.copy()

for h in [1, 3, 6, 12, 24]:
    train_fe[f"wl_diff_{h}h"] = (
        train['wl_t'] - train[f"wl_t_minus_{h}h"]
    )
    val_fe[f"wl_diff_{h}h"] = (
        val['wl_t'] - val[f"wl_t_minus_{h}h"]
    )

display(train_fe.head())
print()
display(val_fe.head())

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,imerg_rain_1h,imerg_rain_6h,imerg_rain_24h,sfc_rain_1h,sfc_rain_6h,sfc_rain_24h,radar_reflectivity_mean,radar_reflectivity_p95,radar_reflectivity_ge20_fraction,cat_area,wsarea,mean_elevation,mean_slope,urban_ratio,forest_ratio,stream_order,target_maxrise_6h,event_id,wl_diff_1h,wl_diff_3h,wl_diff_6h,wl_diff_12h,wl_diff_24h
row_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
TR_000222241,2100-01-01,ST0001,0.29,0.29,0.28,0.28,0.28,0.27,0.000,0.000,0.000,0.0,0.0,0.0,12.162,25.274,0.1445,2.8605,37.0279,124.37,9.6147,11.1141,52.4597,1.9592,0.00,1,0.00,0.01,0.01,0.01,0.02
TR_000288748,2100-01-01,ST0002,0.77,0.76,0.77,0.77,0.76,0.77,0.000,0.000,0.000,0.0,0.0,0.0,0.912,12.060,0.0000,3.9564,42.8163,180.09,16.5687,2.5710,88.0622,1.8000,0.00,1,0.01,0.00,0.00,0.01,0.00
TR_000737576,2100-01-01,ST0003,0.73,0.73,0.74,0.74,0.73,0.73,0.000,0.000,0.000,0.0,0.0,0.0,18.060,30.920,0.5654,4.2240,80.8559,125.04,12.1864,34.3816,56.6211,2.2500,0.00,1,0.00,-0.01,-0.01,0.00,0.00
TR_000651952,2100-01-01,ST0004,1.01,1.01,1.01,1.01,1.01,1.01,0.000,0.000,0.000,0.0,0.0,0.0,0.029,0.000,0.0000,3.2098,252.5946,199.30,13.5951,2.7206,73.1707,2.1207,0.00,1,0.00,0.00,0.00,0.00,0.00
TR_000328380,2100-01-01,ST0005,1.01,1.01,1.01,1.01,1.03,1.06,3.018,7.493,7.497,0.0,0.0,0.0,6.898,21.500,0.0811,3.6470,118.5237,246.72,17.1248,0.4779,88.0002,2.0000,0.03,1,0.00,0.00,0.00,-0.02,-0.05

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,imerg_rain_1h,imerg_rain_6h,imerg_rain_24h,sfc_rain_1h,sfc_rain_6h,sfc_rain_24h,radar_reflectivity_mean,radar_reflectivity_p95,radar_reflectivity_ge20_fraction,cat_area,wsarea,mean_elevation,mean_slope,urban_ratio,forest_ratio,stream_order,target_maxrise_6h,event_id,wl_diff_1h,wl_diff_3h,wl_diff_6h,wl_diff_12h,wl_diff_24h
row_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
TR_000201665,2103-06-15,ST0001,0.22,0.22,0.22,0.22,0.22,0.22,0.0,0.0,0.0,0.0,0.0,0.0,1.101,12.63,0.0176,2.8605,37.0279,124.37,9.6147,11.1141,52.4597,1.9592,0.00,99,0.00,0.00,0.00,0.00,0.00
TR_000711206,2103-06-15,ST0002,0.71,0.71,0.71,0.71,0.70,0.72,0.0,0.0,0.0,0.0,0.0,0.0,0.075,0.00,0.0000,3.9564,42.8163,180.09,16.5687,2.5710,88.0622,1.8000,0.00,99,0.00,0.00,0.00,0.01,-0.01
TR_000298448,2103-06-15,ST0003,0.78,0.78,0.78,0.79,0.78,0.79,0.0,0.0,0.0,0.0,0.0,0.0,1.008,14.50,0.0000,4.2240,80.8559,125.04,12.1864,34.3816,56.6211,2.2500,0.00,99,0.00,0.00,-0.01,0.00,-0.01
TR_000605056,2103-06-15,ST0004,0.29,0.30,0.32,0.32,0.31,0.30,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0000,3.2098,252.5946,199.30,13.5951,2.7206,73.1707,2.1207,0.00,99,-0.01,-0.03,-0.03,-0.02,-0.01
TR_000182126,2103-06-15,ST0005,1.03,1.02,1.03,1.03,1.02,1.04,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0000,3.6470,118.5237,246.72,17.1248,0.4779,88.0002,2.0000,0.03,99,0.01,0.00,0.00,0.01,-0.01

In [9]:
# ============================================================
# 2. 수위 차분 파생변수 생성
# ============================================================
# imerg_int_0to0h = (imerg_rain_00h - imerg_rain_00h)/hours
# sfc_int_0to0h = (sfc_rain_00h - sfc_rain_00h)/hours


for df in [train_fe, val_fe]:

    df['imerg_int_1to6h'] = (df['imerg_rain_6h'] - df['imerg_rain_1h']) / 5
    df['imerg_int_6to24h'] = (df['imerg_rain_24h'] - df['imerg_rain_6h']) / 18

    df['sfc_int_1to6h'] = (df['sfc_rain_6h'] - df['sfc_rain_1h']) / 5
    df['sfc_int_6to24h'] = (df['sfc_rain_24h'] - df['sfc_rain_6h']) / 18

display(train_fe.head())
print()
display(val_fe.head())

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,imerg_rain_1h,imerg_rain_6h,imerg_rain_24h,sfc_rain_1h,sfc_rain_6h,sfc_rain_24h,radar_reflectivity_mean,radar_reflectivity_p95,radar_reflectivity_ge20_fraction,cat_area,wsarea,mean_elevation,mean_slope,urban_ratio,forest_ratio,stream_order,target_maxrise_6h,event_id,wl_diff_1h,wl_diff_3h,wl_diff_6h,wl_diff_12h,wl_diff_24h,imerg_int_1to6h,imerg_int_6to24h,sfc_int_1to6h,sfc_int_6to24h
row_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
TR_000222241,2100-01-01,ST0001,0.29,0.29,0.28,0.28,0.28,0.27,0.000,0.000,0.000,0.0,0.0,0.0,12.162,25.274,0.1445,2.8605,37.0279,124.37,9.6147,11.1141,52.4597,1.9592,0.00,1,0.00,0.01,0.01,0.01,0.02,0.000,0.000000,0.0,0.0
TR_000288748,2100-01-01,ST0002,0.77,0.76,0.77,0.77,0.76,0.77,0.000,0.000,0.000,0.0,0.0,0.0,0.912,12.060,0.0000,3.9564,42.8163,180.09,16.5687,2.5710,88.0622,1.8000,0.00,1,0.01,0.00,0.00,0.01,0.00,0.000,0.000000,0.0,0.0
TR_000737576,2100-01-01,ST0003,0.73,0.73,0.74,0.74,0.73,0.73,0.000,0.000,0.000,0.0,0.0,0.0,18.060,30.920,0.5654,4.2240,80.8559,125.04,12.1864,34.3816,56.6211,2.2500,0.00,1,0.00,-0.01,-0.01,0.00,0.00,0.000,0.000000,0.0,0.0
TR_000651952,2100-01-01,ST0004,1.01,1.01,1.01,1.01,1.01,1.01,0.000,0.000,0.000,0.0,0.0,0.0,0.029,0.000,0.0000,3.2098,252.5946,199.30,13.5951,2.7206,73.1707,2.1207,0.00,1,0.00,0.00,0.00,0.00,0.00,0.000,0.000000,0.0,0.0
TR_000328380,2100-01-01,ST0005,1.01,1.01,1.01,1.01,1.03,1.06,3.018,7.493,7.497,0.0,0.0,0.0,6.898,21.500,0.0811,3.6470,118.5237,246.72,17.1248,0.4779,88.0002,2.0000,0.03,1,0.00,0.00,0.00,-0.02,-0.05,0.895,0.000222,0.0,0.0

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,imerg_rain_1h,imerg_rain_6h,imerg_rain_24h,sfc_rain_1h,sfc_rain_6h,sfc_rain_24h,radar_reflectivity_mean,radar_reflectivity_p95,radar_reflectivity_ge20_fraction,cat_area,wsarea,mean_elevation,mean_slope,urban_ratio,forest_ratio,stream_order,target_maxrise_6h,event_id,wl_diff_1h,wl_diff_3h,wl_diff_6h,wl_diff_12h,wl_diff_24h,imerg_int_1to6h,imerg_int_6to24h,sfc_int_1to6h,sfc_int_6to24h
row_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
TR_000201665,2103-06-15,ST0001,0.22,0.22,0.22,0.22,0.22,0.22,0.0,0.0,0.0,0.0,0.0,0.0,1.101,12.63,0.0176,2.8605,37.0279,124.37,9.6147,11.1141,52.4597,1.9592,0.00,99,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0
TR_000711206,2103-06-15,ST0002,0.71,0.71,0.71,0.71,0.70,0.72,0.0,0.0,0.0,0.0,0.0,0.0,0.075,0.00,0.0000,3.9564,42.8163,180.09,16.5687,2.5710,88.0622,1.8000,0.00,99,0.00,0.00,0.00,0.01,-0.01,0.0,0.0,0.0,0.0
TR_000298448,2103-06-15,ST0003,0.78,0.78,0.78,0.79,0.78,0.79,0.0,0.0,0.0,0.0,0.0,0.0,1.008,14.50,0.0000,4.2240,80.8559,125.04,12.1864,34.3816,56.6211,2.2500,0.00,99,0.00,0.00,-0.01,0.00,-0.01,0.0,0.0,0.0,0.0
TR_000605056,2103-06-15,ST0004,0.29,0.30,0.32,0.32,0.31,0.30,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0000,3.2098,252.5946,199.30,13.5951,2.7206,73.1707,2.1207,0.00,99,-0.01,-0.03,-0.03,-0.02,-0.01,0.0,0.0,0.0,0.0
TR_000182126,2103-06-15,ST0005,1.03,1.02,1.03,1.03,1.02,1.04,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0000,3.6470,118.5237,246.72,17.1248,0.4779,88.0002,2.0000,0.03,99,0.01,0.00,0.00,0.01,-0.01,0.0,0.0,0.0,0.0

In [10]:
# ============================================================
# 2. 데이터셋 저장하기
# ============================================================

train_fe.to_parquet(PROJECT_ROOT / 'parqueted_data' / '1_train_fe.parquet')
val_fe.to_parquet(PROJECT_ROOT / 'parqueted_data' / '1_val_fe.parquet')