In [1]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent

import pandas as pd

# pd.set_option('display.max_columns', None)  # none은 제한값 자리(몇개 열까지 보여줄까)
# pd.set_option('display.max_rows', None)

# 1-1. 데이터 불러오기
train = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / 'train_split')
val = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / 'val_split')

from sklearn import set_config
set_config(display='text')
# scikit-learn의 HTML 출력 과정에서 발생한 cp949 간 UTF-8 충돌 때문에 넣는 코드

In [ ]:
# train셋
display(pd.concat([
    train['cat_area']
        .drop_duplicates()
        .sort_values(ascending = False)
        .reset_index(drop=True),

    train['wsarea']
    .drop_duplicates()
    .sort_values(ascending = False)
    .reset_index(drop=True)
], axis = 1
))

# val셋
pd.concat([
    val['cat_area']
        .drop_duplicates()
        .sort_values(ascending = False)
        .reset_index(drop=True),

    val['wsarea']
    .drop_duplicates()
    .sort_values(ascending = False)
    .reset_index(drop=True)
], axis = 1
)

# 이상치는 train, val이 서로 같아서 하나의 관측소로 판단됨

     cat_area      wsarea
0     50.6527  29687.6916
1     18.6391  11684.3950
2     15.8718  10766.0188
3     11.8928   9037.7681
4     11.3891   7888.0657
..        ...         ...
324    2.4657      9.8050
325    2.3503      7.3666
326    2.3451      6.3167
327    2.3403      5.7516
328    2.2603         NaN

[329 rows x 2 columns]

     cat_area      wsarea
0     50.6527  29687.6916
1     18.6391  11684.3950
2     15.8718  10766.0188
3     11.8928   9037.7681
4     11.3891   7888.0657
..        ...         ...
324    2.4657      9.8050
325    2.3503      7.3666
326    2.3451      6.3167
327    2.3403      5.7516
328    2.2603         NaN

[329 rows x 2 columns]

In [ ]:
# cat_area, wsarea 이상치 기준
# cat_area는 50 이상
# wsarea는 20000 이상

cond_cat_out = train['cat_area'] > 50
cond_wsarea_out = train['wsarea'] > 20000
extreme_station = train.loc[cond_cat_out | cond_wsarea_out]['station_id']

print(extreme_station.unique())  # 'ST0051'

<ArrowStringArray>
['ST0051']
Length: 1, dtype: str