In [13]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent

import pandas as pd


pd.set_option('display.max_columns', None)  # none은 제한값 자리(몇개 열까지 보여줄까)
pd.set_option('display.max_rows', None)


# ============================================================
# 0. 데이터 불러오기: 2-5 train_test_comparison에서 제거된 이상치까지 반영된 데이터셋
# ============================================================

train = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / '3_train_clean3.parquet')
val = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / '3_val_clean3.parquet')

test = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / '1_test_fe.parquet')

print(train.shape, val.shape)

from sklearn import set_config
set_config(display='text')
# scikit-learn의 HTML 출력 과정에서 발생한 cp949 간 UTF-8 충돌 때문에 넣는 코드

(616293, 35) (133316, 35)

In [20]:
# ============================================================
# 0. 라이브러리 불러오기
# ============================================================

import numpy as np
import optuna

from catboost import CatBoostRegressor
from sklearn.metrics import root_mean_squared_error

c:\Users\20162180\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [21]:
# ============================================================
# 1. 컬럼군 정의
# ============================================================

target_col = 'target_maxrise_6h'  # 모델링 학습부터는 반드시 빼내야 함

# 수위 컬럼군
wl_cols = [
    'wl_t',
    'wl_t_minus_1h',
    'wl_t_minus_3h',
    'wl_t_minus_6h',
    'wl_t_minus_12h',
    'wl_t_minus_24h',
]

# 수위차분(wl_diff) 컬럼군
wl_diff_cols = [
    'wl_t',
    'wl_diff_1h',
    'wl_diff_3h',
    'wl_diff_6h',
    'wl_diff_12h',
    'wl_diff_24h'
]


# 강수 컬럼군
rain_cols = [
    # IMERG강우
    'imerg_rain_1h',
    'imerg_rain_6h',
    'imerg_rain_24h',
    # 지상강우
    'sfc_rain_1h',
    'sfc_rain_6h',
    'sfc_rain_24h',
    # 레이더 반사도
    'radar_reflectivity_mean',
    'radar_reflectivity_p95',
    'radar_reflectivity_ge20_fraction'
]

# 강우강도 컬럼군
rain_int_cols = [
    'imerg_rain_1h',
    'imerg_int_1to6h',
    'imerg_int_6to24h',
    'sfc_rain_1h',
    'sfc_int_1to6h',
    'sfc_int_6to24h'
]

# 환경 컬럼군
env_cols = [
    'cat_area',       # km²
    'wsarea',         # km²
    'mean_elevation', # m
    'mean_slope',     # °
    'urban_ratio',    # %
    'forest_ratio',   # %
    'stream_order'
]

num_cols = wl_cols + rain_cols + env_cols
num_cols_fe_wl = num_cols + [
    col for col in wl_diff_cols if col != 'wl_t'
]
num_cols_fe = num_cols_fe_wl + [
    col for col in rain_int_cols if col not in ['imerg_rain_1h', 'sfc_rain_1h']
]

print(f"""<변수개수 검증>
    수위변수: {len(wl_cols)}
    강우변수: {len(rain_cols)}, 
    환경변수: {len(env_cols)}, 
    수위차분(wl_t포함): {len(wl_diff_cols)},
    강우강도(rain_1h포함): {len(rain_int_cols)}
    기존 숫자열(수위 + 강우 + 환경): {len(num_cols)}, 
    수위차분추가 숫자열(수위 + 강우 + 환경 + 수위차분(wl_t제외)): {len(num_cols_fe_wl)},
    강우강도추가 숫자열(수위차분추가 숫자열 + 강우강도(rain_1h 2개제외)): {len(num_cols_fe)}
""")

<변수개수 검증>
    수위변수: 6
    강우변수: 9,
    환경변수: 7,
    수위차분(wl_t포함): 6,
    강우강도(rain_1h포함): 6
    기존 숫자열(수위 + 강우 + 환경): 22,
    수위차분추가 숫자열(수위 + 강우 + 환경 + 수위차분(wl_t제외)): 27,
    강우강도추가 숫자열(수위차분추가 숫자열 + 강우강도(rain_1h 2개제외)): 31

In [4]:
# ============================================================
# 2. 종속변수 설정
# ============================================================

y_train = train[target_col]
y_val = val[target_col]

In [ ]:
# ============================================================
# 3. 최종모델(15) + 데이터셋 필터링
# ============================================================
# wl_diff_6h < -n 인 train, val 제거하고 진행

train_filtered = train.loc[
    train['wl_diff_6h'] >= -1
].copy()

val_filtered = val.loc[
    val['wl_diff_6h'] >= -1
].copy()

print('Train:', train.shape, '->', train_filtered.shape)
print('Validation:', val.shape, '->', val_filtered.shape)

print('Train 제거 행:', len(train) - len(train_filtered))
print('Validation 제거 행:', len(val) - len(val_filtered))

# ============================================================
# 2. 종속변수 설정
# ============================================================

y_train = train_filtered[target_col]
y_val = val_filtered[target_col]


# station_id가 포함된 데이터셋 생성
# 기존 데이터와의 연결 차단을 위해 .copy() 사용
X_train_with_station = train_filtered[num_cols_fe + ['station_id']].copy()
X_val_with_station = val_filtered[num_cols_fe + ['station_id']].copy()

# CatBoost 전용 범주형 변수 취급: str로 자료형 변환
X_train_with_station['station_id'] = X_train_with_station['station_id'].astype(str)
X_val_with_station['station_id'] = X_val_with_station['station_id'].astype(str)

# 모델 정의
model_base_no_ohe = CatBoostRegressor(
    random_state=42,
    iterations=3000,
    cat_features=['station_id']
)

# 학습
model_base_no_ohe.fit(
    X_train_with_station,
    y_train,
    early_stopping_rounds=100,
    eval_set=(X_val_with_station, y_val),
    verbose=200
)

# 예측
pred_val_no_ohe = model_base_no_ohe.predict(X_val_with_station)
pred_train_no_ohe = model_base_no_ohe.predict(X_train_with_station)

print('Best iteration:', model_base_no_ohe.best_iteration_)
print('Tree count:', model_base_no_ohe.tree_count_)
print('Best score:', model_base_no_ohe.best_score_['validation']['RMSE'])
print()

rmse_val_no_ohe = root_mean_squared_error(
    y_val, pred_val_no_ohe
)

rmse_train_no_ohe = root_mean_squared_error(
    y_train, pred_train_no_ohe
)

print('val RMSE: ', rmse_val_no_ohe)
print('train RMSE: ', rmse_train_no_ohe)
print(
    'Gap: ',
    rmse_val_no_ohe - rmse_train_no_ohe
)

Train: (616293, 35) -> (610970, 35)
Validation: (133316, 35) -> (132190, 35)
Train 제거 행: 5323
Validation 제거 행: 1126
Learning rate set to 0.071327
0:	learn: 0.3046440	test: 0.2481225	best: 0.2481225 (0)	total: 175ms	remaining: 8m 45s
200:	learn: 0.2223323	test: 0.1940703	best: 0.1940703 (200)	total: 32s	remaining: 7m 25s
400:	learn: 0.2115546	test: 0.1905899	best: 0.1905899 (400)	total: 1m 4s	remaining: 6m 55s
600:	learn: 0.2048428	test: 0.1893610	best: 0.1893610 (600)	total: 1m 43s	remaining: 6m 54s
800:	learn: 0.1998609	test: 0.1888210	best: 0.1887844 (798)	total: 2m 20s	remaining: 6m 24s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.1885875302
bestIteration = 839

Shrink model to first 840 iterations.
Best iteration: 839
Tree count: 840
Best score: 0.18858753018474964

val RMSE:  0.18858753013891283
train RMSE:  0.19815320147553897
Gap:  -0.009565671336626141

In [14]:
# ============================================================
# 4. 최종모델(15) + 데이터셋 필터링 + 필터링된 행의 복원
# ============================================================
# wl_diff_6h < -n 인 train, val 제거하고 진행
# 위 조건에 해당하는 행은 종속변수로 -wl_diff_6h을 넣음

# 필터링 전 데이터 개수
print('=== 필터링 전 ===')
print('Train:', len(train))
print('Validation:', len(val))
print()

# 필터링
train_filtered = train.loc[
    train['wl_diff_6h'] >= -6
].copy()

val_filtered = val.loc[
    val['wl_diff_6h'] >= -6
].copy()

# 필터링 후 데이터 개수
print('=== 필터링 후 ===')
print('Train:', len(train_filtered))
print('Validation:', len(val_filtered))
print('Train 제거 행:', len(train) - len(train_filtered))
print('Validation 제거 행:', len(val) - len(val_filtered))
print()
print()

# ============================================================
# 2.필터링 후, 종속변수 설정
# ============================================================

y_train = train_filtered[target_col]
y_val = val_filtered[target_col]


# station_id가 포함된 데이터셋 생성
# 기존 데이터와의 연결 차단을 위해 .copy() 사용
X_train_with_station = train_filtered[num_cols_fe + ['station_id']].copy()
X_val_with_station = val_filtered[num_cols_fe + ['station_id']].copy()

# CatBoost 전용 범주형 변수 취급: str로 자료형 변환
X_train_with_station['station_id'] = X_train_with_station['station_id'].astype(str)
X_val_with_station['station_id'] = X_val_with_station['station_id'].astype(str)

# 모델 정의
model_base_no_ohe = CatBoostRegressor(
    random_state=42,
    iterations=3000,
    cat_features=['station_id']
)

# 학습
model_base_no_ohe.fit(
    X_train_with_station,
    y_train,
    early_stopping_rounds=100,
    eval_set=(X_val_with_station, y_val),
    verbose=200
)

# ============================================================
# 4. 예측 및 RMSE 비교
# ============================================================

# 필터링된 데이터 예측
pred_val_no_ohe = model_base_no_ohe.predict(X_val_with_station)

print('Best iteration:', model_base_no_ohe.best_iteration_)
print('Tree count:', model_base_no_ohe.tree_count_)
print('Best score:', model_base_no_ohe.best_score_['validation']['RMSE'])
print()
print()

# 제외된 행에 -wl_diff_6h을 넣고자 일단 전부 다 넣은 df
pred_val_all = -val['wl_diff_6h'].copy()

# 필터링 모델링 예측 행은 다시 덮어쓰기
pred_val_all.loc[val_filtered.index] = pred_val_no_ohe

# 데이터 개수 검증
print('모두 합친 뒤 최종 Validation:', len(pred_val_all))
print()

assert len(pred_val_all) == len(val)
assert pred_val_all.index.equals(val.index)

rmse_val_no_ohe = root_mean_squared_error(
    val[target_col], pred_val_all
)

print('val RMSE: ', rmse_val_no_ohe)

=== 필터링 전 ===
Train: 616293
Validation: 133316

=== 필터링 후 ===
Train: 616170
Validation: 133293
Train 제거 행: 123
Validation 제거 행: 23


Learning rate set to 0.071422
0:	learn: 0.3803574	test: 0.3352320	best: 0.3352320 (0)	total: 184ms	remaining: 9m 10s
200:	learn: 0.2302780	test: 0.2031879	best: 0.2031879 (200)	total: 34.1s	remaining: 7m 54s
400:	learn: 0.2181291	test: 0.1974544	best: 0.1974478 (399)	total: 1m 8s	remaining: 7m 22s
600:	learn: 0.2107126	test: 0.1951323	best: 0.1951323 (600)	total: 1m 47s	remaining: 7m 9s
800:	learn: 0.2053392	test: 0.1940873	best: 0.1940784 (785)	total: 2m 19s	remaining: 6m 21s
1000:	learn: 0.2010959	test: 0.1934240	best: 0.1934240 (1000)	total: 2m 52s	remaining: 5m 44s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.1933117859
bestIteration = 1065

Shrink model to first 1066 iterations.
Best iteration: 1065
Tree count: 1066
Best score: 0.1933117858839308


모두 합친 뒤 최종 Validation: 133316

val RMSE:  0.19358381327496477

In [15]:
# 분석 대상 관측소
stations = ['ST0358', 'ST0292', 'ST0326']

for name, df in [
    ('Train', train),
    ('Val', val)

]:
    for station in stations:
        data = df.loc[
            ((df['station_id'] == station) & (df['wl_diff_6h'] < -4)),
            ['timestamp', 'station_id'] + wl_cols + [target_col]
        ]

        print(f'\n{name} | {station} | {len(data):,}개')
        display(data)

#     ('Test', test)

Train | ST0358 | 311개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000561359,2100-01-01 01:00:00,ST0358,-1.66,-0.45,1.91,2.55,-1.69,-2.12,4.30
TR_000164077,2100-01-21 07:00:00,ST0358,-2.24,-1.44,2.01,3.79,-2.17,-2.33,5.99
TR_000225662,2100-01-21 08:00:00,ST0358,-2.29,-2.24,0.34,3.98,-2.18,-2.33,6.36
TR_000368174,2100-01-21 09:00:00,ST0358,-2.29,-2.29,-1.44,3.30,-2.19,-2.41,6.36
TR_000388142,2100-01-31 09:00:00,ST0358,-1.55,-0.98,0.94,2.94,-1.66,-0.79,4.01
TR_000257547,2100-01-31 21:00:00,ST0358,-2.00,-1.27,0.62,2.46,-1.55,-1.66,5.00
TR_000026925,2100-01-31 22:00:00,ST0358,-2.27,-2.00,-0.35,2.27,-1.39,-0.81,5.60
TR_000062299,2100-02-01 09:00:00,ST0358,-1.47,-0.45,2.28,3.00,-2.00,-1.55,3.56
TR_000686641,2100-02-01 10:00:00,ST0358,-2.22,-1.47,1.00,3.33,-2.27,-1.39,4.95
TR_000074970,2100-02-01 11:00:00,ST0358,-1.93,-2.22,-0.45,3.03,-2.03,-0.82,4.66
TR_000329890,2100-02-10 00:00:00,ST0358,-1.89,-1.52,0.39,2.56,-1.50,-1.50,4.74
TR_000337175,2100-02-20 00:00:00,ST0358,-2.59,-2.90,-1.90,2.65,-1.87,-1.50,6.13
TR_000195792,2100-03-02 05:00:00,ST0358,-1.58,-0.40,2.11,3.17,-2.83,-2.61,3.80
TR_000153527,2100-03-02 06:00:00,ST0358,-2.22,-1.58,0.89,3.43,-2.87,-3.00,4.79
TR_000244562,2100-03-02 07:00:00,ST0358,-2.55,-2.22,-0.40,2.99,-2.86,-2.63,5.12
TR_000018762,2100-04-01 09:00:00,ST0358,-1.68,-0.57,2.08,2.81,-1.42,-2.22,4.16
TR_000447253,2100-04-01 10:00:00,ST0358,-2.13,-1.68,0.83,3.23,-2.12,-2.21,5.27
TR_000144132,2100-04-01 11:00:00,ST0358,-2.12,-2.13,-0.57,2.91,-2.05,-2.21,5.38
TR_000378026,2100-04-01 22:00:00,ST0358,-1.27,-0.40,1.87,3.14,-2.13,-2.12,3.77
TR_000166713,2100-04-01 23:00:00,ST0358,-1.73,-1.27,0.79,3.26,-2.12,-2.05,4.44
TR_000151391,2100-04-02 00:00:00,ST0358,-1.43,-1.73,-0.40,2.77,-1.45,-1.05,4.14
TR_000656489,2100-04-02 11:00:00,ST0358,-1.69,-1.33,0.52,2.71,-1.73,-2.12,4.51
TR_000151349,2100-04-02 12:00:00,ST0358,-1.98,-1.69,-0.54,2.21,-1.43,-1.45,4.80
TR_000462624,2100-04-11 01:00:00,ST0358,-1.76,-0.59,2.26,3.49,-1.80,-1.90,4.91
TR_000663093,2100-04-11 02:00:00,ST0358,-2.14,-1.76,0.93,3.61,-2.16,-2.01,5.52
TR_000697773,2100-04-11 03:00:00,ST0358,-2.15,-2.14,-0.59,3.27,-1.92,-1.37,5.53
TR_000233326,2100-05-31 01:00:00,ST0358,-2.21,-1.45,0.90,2.72,-2.17,-1.86,5.31
TR_000419106,2100-05-31 02:00:00,ST0358,-2.41,-2.21,-0.34,2.60,-2.15,-1.24,5.58
TR_000419790,2100-06-30 03:00:00,ST0358,-2.04,-1.34,1.91,2.89,-1.85,-2.07,5.26
TR_000022874,2100-06-30 04:00:00,ST0358,-2.03,-2.04,0.18,3.21,-2.04,-2.10,6.20
TR_000544152,2100-06-30 05:00:00,ST0358,-2.03,-2.03,-1.34,2.69,-2.03,-2.20,6.26
TR_000394980,2100-06-30 16:00:00,ST0358,-1.04,-0.25,2.36,4.17,-2.03,-2.04,4.08
TR_000667037,2100-06-30 17:00:00,ST0358,-1.85,-1.04,0.99,4.23,-2.03,-2.03,4.89
TR_000201620,2100-06-30 18:00:00,ST0358,-1.16,-1.85,-0.25,3.47,-2.03,-1.71,4.20
TR_000069978,2100-07-10 00:00:00,ST0358,-2.17,-2.27,-2.21,3.05,-2.31,-2.38,6.78
TR_000636228,2100-08-09 00:00:00,ST0358,-1.92,-0.36,3.04,4.17,-2.13,-2.22,5.00
TR_000463729,2100-08-09 01:00:00,ST0358,-2.23,-1.92,1.40,4.58,-2.12,-2.24,6.02
TR_000716800,2100-08-09 02:00:00,ST0358,-2.23,-2.23,-0.36,4.17,-2.12,-2.33,6.02
TR_000193958,2100-08-09 03:00:00,ST0358,-2.21,-2.23,-1.92,3.04,-2.05,-1.74,6.00
TR_000558402,2100-08-09 12:00:00,ST0358,-2.12,-0.93,2.36,3.08,-1.92,-2.13,5.20
TR_000559314,2100-08-09 13:00:00,ST0358,-2.12,-2.12,0.89,3.79,-2.23,-2.12,6.16
TR_000682432,2100-08-09 14:00:00,ST0358,-2.12,-2.12,-0.93,3.38,-2.23,-2.12,6.19
TR_000066782,2100-08-09 15:00:00,ST0358,-2.12,-2.12,-2.12,2.36,-2.21,-2.05,6.19
TR_000425953,2100-08-19 08:00:00,ST0358,-1.75,-0.01,3.39,3.88,-2.50,-2.61,5.09
TR_000695792,2100-08-19 09:00:00,ST0358,-2.61,-1.75,1.83,4.67,-2.68,-2.61,6.95
TR_000639807,2100-08-19 10:00:00,ST0358,-2.63,-2.61,-0.01,4.40,-2.67,-2.62,6.97
TR_000290451,2100-08-19 11:00:00,ST0358,-2.61,-2.63,-1.75,3.39,-2.53,-1.92,6.95
TR_000365679,2100-08-29 02:00:00,ST0358,-2.14,-0.83,2.20,2.94,-1.55,-2.17,4.93
TR_000219769,2100-09-08 03:00:00,ST0358,-1.22,0.82,4.11,2.87,-1.66,-2.20,3.23
TR_000657571,2100-09-08 04:00:00,ST0358,-2.29,-1.22,2.69,4.57,-2.24,-2.36,6.35
TR_000131111,2100-09-08 05:00:00,ST0358,-2.29,-2.29,0.82,4.82,-2.22,-2.37,7.00
TR_000153080,2100-09-08 06:00:00,ST0358,-2.31,-2.29,-1.22,4.11,-2.24,-2.42,7.02
TR_000074719,2100-09-08 07:00:00,ST0358,-2.45,-2.31,-2.29,2.69,-1.98,-1.46,7.16
TR_000321000,2100-09-08 16:00:00,ST0358,-2.08,-0.40,3.24,4.06,-2.29,-2.24,5.55
TR_000288965,2100-09-08 17:00:00,ST0358,-2.25,-2.08,1.53,4.71,-2.29,-2.22,6.63
TR_000363529,2100-09-08 18:00:00,ST0358,-2.23,-2.25,-0.40,4.32,-2.31,-2.24,6.61
TR_000490402,2100-09-08 19:00:00,ST0358,-2.24,-2.23,-2.08,3.24,-2.45,-1.98,6.62
TR_000084040,2100-10-08 00:00:00,ST0358,-1.37,-0.58,1.60,2.83,-2.01,-1.54,3.88
TR_000076857,2100-10-08 01:00:00,ST0358,-1.63,-1.37,0.42,2.91,-1.84,-0.86,4.39
TR_000745938,2100-10-08 12:00:00,ST0358,-2.25,-0.55,1.61,2.51,-1.37,-2.01,4.60
TR_000716502,2100-10-08 13:00:00,ST0358,-2.33,-2.25,0.78,2.76,-1.63,-1.84,5.40
TR_000131952,2100-10-08 14:00:00,ST0358,-2.27,-2.33,-0.55,2.38,-1.26,-1.03,5.52
TR_000109422,2100-11-07 04:00:00,ST0358,-2.05,-0.90,1.82,2.71,-1.33,-2.33,4.83
TR_000664378,2100-11-07 05:00:00,ST0358,-2.33,-2.05,0.41,2.97,-1.95,-2.27,6.02
TR_000265179,2100-11-07 06:00:00,ST0358,-2.32,-2.33,-0.90,2.61,-1.52,-1.60,6.26
TR_000655304,2100-12-07 06:00:00,ST0358,-1.65,-0.20,3.26,4.32,-2.14,-2.29,5.18
TR_000742704,2100-12-07 07:00:00,ST0358,-2.19,-1.65,1.54,5.01,-2.14,-2.31,6.90
TR_000426823,2100-12-07 08:00:00,ST0358,-2.23,-2.19,-0.20,4.48,-2.13,-2.33,6.94
TR_000326895,2100-12-07 09:00:00,ST0358,-2.24,-2.23,-1.65,3.26,-2.13,-2.08,6.95
TR_000344066,2100-12-07 18:00:00,ST0358,-1.68,0.20,3.64,3.53,-1.65,-2.14,4.59
TR_000130017,2100-12-07 19:00:00,ST0358,-2.08,-1.68,2.16,4.71,-2.19,-2.14,6.44
TR_000133968,2100-12-07 20:00:00,ST0358,-2.09,-2.08,0.20,4.45,-2.23,-2.13,6.57
TR_000715013,2100-12-07 21:00:00,ST0358,-2.09,-2.09,-1.68,3.64,-2.24,-2.13,6.57
TR_000333045,2100-12-08 07:00:00,ST0358,-2.24,-0.93,2.42,4.36,-2.08,-2.19,6.13
TR_000660806,2100-12-08 08:00:00,ST0358,-2.27,-2.24,0.64,4.48,-2.09,-2.23,6.65
TR_000053157,2100-12-08 09:00:00,ST0358,-2.23,-2.27,-0.93,3.83,-2.09,-2.24,6.61
TR_000086103,2100-12-08 10:00:00,ST0358,-2.07,-2.23,-2.24,2.42,-1.54,-1.06,6.45
TR_000729634,2100-12-08 19:00:00,ST0358,-1.34,0.11,3.10,3.89,-2.24,-2.08,4.50
TR_000327902,2100-12-08 20:00:00,ST0358,-1.88,-1.34,1.52,4.38,-2.27,-2.09,5.76
TR_000558872,2100-12-08 21:00:00,ST0358,-2.12,-1.88,0.11,4.07,-2.23,-2.09,6.00
TR_000404504,2100-12-08 22:00:00,ST0358,-1.98,-2.12,-1.34,3.10,-2.07,-1.54,5.86
TR_000576162,2100-12-09 07:00:00,ST0358,-1.19,-0.16,2.79,3.16,-1.34,-2.24,3.65
TR_000670257,2100-12-09 08:00:00,ST0358,-2.12,-1.19,1.54,3.88,-1.88,-2.27,5.65
TR_000174364,2100-12-09 09:00:00,ST0358,-2.14,-2.12,-0.16,3.62,-2.12,-2.23,5.92
TR_000557265,2100-12-09 10:00:00,ST0358,-1.80,-2.14,-1.19,2.79,-1.98,-2.07,5.58
TR_000431976,2100-12-27 04:00:00,ST0358,-1.32,0.33,3.60,3.95,-2.85,-2.40,3.88
TR_000147687,2100-12-27 05:00:00,ST0358,-2.66,-1.32,2.08,4.67,-2.86,-2.87,6.41
TR_000045647,2100-12-27 06:00:00,ST0358,-2.84,-2.66,0.33,4.52,-2.86,-2.59,6.59
TR_000703525,2100-12-27 07:00:00,ST0358,-2.75,-2.84,-1.32,3.60,-2.17,-1.18,6.50
TR_000184125,2101-01-26 00:00:00,ST0358,-1.87,-0.61,1.86,4.14,-2.25,-1.27,4.76
TR_000221198,2101-02-15 00:00:00,ST0358,-2.87,-2.88,-0.48,4.14,-2.99,-2.87,7.56
TR_000172949,2101-02-15 01:00:00,ST0358,-2.88,-2.87,-2.28,3.20,-3.00,-2.86,7.57
TR_000336035,2101-02-25 02:00:00,ST0358,-1.17,0.45,3.36,3.41,-0.44,-2.04,3.36
TR_000083055,2101-02-25 03:00:00,ST0358,-2.40,-1.17,2.00,4.12,-2.36,-2.64,5.70
TR_000548462,2101-03-07 03:00:00,ST0358,-2.17,-0.84,3.25,4.69,-2.07,-2.16,6.42
TR_000219301,2101-03-07 04:00:00,ST0358,-2.19,-2.17,1.34,5.21,-2.08,-2.22,7.61
TR_000358447,2101-03-07 05:00:00,ST0358,-2.19,-2.19,-0.84,4.57,-2.07,-2.26,7.61
TR_000668607,2101-03-07 06:00:00,ST0358,-2.19,-2.19,-2.17,3.25,-2.08,-2.07,7.61
TR_000304227,2101-03-07 15:00:00,ST0358,-1.68,0.32,4.07,4.25,-2.17,-2.07,5.28
TR_000200353,2101-03-07 16:00:00,ST0358,-2.08,-1.68,2.31,5.42,-2.19,-2.08,7.13
TR_000730672,2101-03-07 17:00:00,ST0358,-2.08,-2.08,0.32,5.11,-2.19,-2.07,7.13
TR_000426886,2101-03-07 18:00:00,ST0358,-2.08,-2.08,-1.68,4.07,-2.19,-2.08,7.13
TR_000049940,2101-03-08 03:00:00,ST0358,-1.59,0.53,4.08,3.60,-1.68,-2.17,3.99
TR_000622387,2101-03-08 04:00:00,ST0358,-2.07,-1.59,2.44,5.05,-2.08,-2.19,6.41
TR_000515782,2101-03-08 05:00:00,ST0358,-2.07,-2.07,0.53,5.04,-2.08,-2.19,6.96
TR_000684227,2101-03-08 06:00:00,ST0358,-2.08,-2.07,-1.59,4.08,-2.08,-2.19,6.97
TR_000135795,2101-03-08 07:00:00,ST0358,-2.07,-2.08,-2.07,2.44,-1.41,-0.97,6.96
TR_000194946,2101-03-08 16:00:00,ST0358,-1.83,-0.25,3.09,4.34,-2.07,-2.08,5.34
TR_000043618,2101-03-08 17:00:00,ST0358,-2.07,-1.83,1.41,4.89,-2.07,-2.08,6.26
TR_000412188,2101-03-08 18:00:00,ST0358,-2.11,-2.07,-0.25,4.36,-2.08,-2.08,6.30
TR_000341762,2101-03-08 19:00:00,ST0358,-2.10,-2.11,-1.83,3.09,-2.07,-1.41,6.29
TR_000217453,2101-03-17 00:00:00,ST0358,-1.90,-1.13,1.14,3.53,-2.47,-2.53,4.48
TR_000543506,2101-03-17 01:00:00,ST0358,-2.02,-1.90,-0.15,3.19,-2.03,-1.56,4.60
TR_000667047,2101-04-06 01:00:00,ST0358,-1.87,-1.21,0.77,2.18,-1.26,-1.67,5.07
TR_000371672,2101-04-06 02:00:00,ST0358,-2.17,-1.87,-0.37,2.19,-1.42,-0.98,5.79
TR_000545413,2101-04-16 05:00:00,ST0358,-1.81,-0.62,2.30,3.27,-2.33,-2.13,4.99
TR_000189566,2101-04-16 06:00:00,ST0358,-2.11,-1.81,0.88,3.61,-2.31,-2.14,5.72
TR_000515612,2101-04-16 07:00:00,ST0358,-2.11,-2.11,-0.62,3.21,-2.27,-2.14,5.72
TR_000375564,2101-05-16 04:00:00,ST0358,-1.85,-0.83,1.62,3.25,-2.86,-3.00,3.95
TR_000364338,2101-05-16 05:00:00,ST0358,-2.68,-1.85,0.54,3.28,-2.85,-2.70,5.11
TR_000226138,2101-05-16 06:00:00,ST0358,-2.21,-2.68,-0.83,2.78,-1.88,-1.58,4.64
TR_000186912,2101-05-26 07:00:00,ST0358,-1.39,-0.51,1.68,2.95,-2.06,-1.36,4.05
TR_000181024,2101-05-26 08:00:00,ST0358,-1.51,-1.39,0.50,2.91,-1.75,-0.83,4.25
TR_000456552,2101-05-26 19:00:00,ST0358,-1.86,-0.87,1.41,2.66,-1.39,-2.06,4.61
TR_000008608,2101-06-05 04:00:00,ST0358,-2.13,-1.10,2.04,2.92,-1.56,-2.14,5.47
TR_000434590,2101-06-05 05:00:00,ST0358,-2.13,-2.13,0.57,3.45,-2.24,-2.13,6.39
TR_000636155,2101-06-05 06:00:00,ST0358,-2.13,-2.13,-1.10,3.00,-2.25,-2.13,6.42
TR_000438306,2101-06-05 07:00:00,ST0358,-2.14,-2.13,-2.13,2.04,-1.67,-1.03,6.43
TR_000659083,2101-06-05 16:00:00,ST0358,-0.89,0.69,3.57,3.34,-2.13,-1.56,2.96
TR_000510533,2101-06-05 17:00:00,ST0358,-2.20,-0.89,2.25,4.26,-2.13,-2.24,5.42
TR_000717829,2101-06-05 18:00:00,ST0358,-2.25,-2.20,0.69,4.29,-2.13,-2.25,5.64
TR_000611311,2101-07-05 05:00:00,ST0358,-1.33,-0.05,3.16,3.38,-2.04,-2.32,4.59
TR_000059881,2101-07-05 06:00:00,ST0358,-2.27,-1.33,1.65,4.32,-2.30,-2.40,6.97
TR_000699317,2101-07-05 07:00:00,ST0358,-2.31,-2.27,-0.05,4.10,-2.29,-2.45,7.08
TR_000604627,2101-07-05 08:00:00,ST0358,-2.31,-2.31,-1.33,3.16,-2.30,-2.50,7.08
TR_000426656,2101-08-04 00:00:00,ST0358,-1.85,-2.14,0.10,2.67,-1.87,-1.68,4.79
TR_000366275,2101-08-04 11:00:00,ST0358,-1.42,-0.66,1.45,2.94,-2.14,-2.02,3.78
TR_000279349,2101-08-04 12:00:00,ST0358,-1.55,-1.42,0.41,2.88,-1.85,-1.87,4.20
TR_000056828,2101-08-05 00:00:00,ST0358,-1.41,-0.80,1.12,2.65,-1.55,-1.85,4.26
TR_000092501,2101-08-05 12:00:00,ST0358,-1.38,-0.67,1.37,2.85,-1.41,-1.55,3.60
TR_000184722,2101-08-14 01:00:00,ST0358,-2.06,-0.63,2.80,4.12,-2.21,-2.10,5.35
TR_000494549,2101-09-03 00:00:00,ST0358,-2.48,-2.38,-2.38,2.40,-1.59,-1.16,7.07
TR_000569569,2101-09-13 07:00:00,ST0358,-2.61,-1.28,2.35,3.75,-2.36,-2.63,6.61
TR_000350316,2101-09-13 08:00:00,ST0358,-2.62,-2.61,0.63,4.04,-2.67,-2.63,7.35
TR_000146666,2101-09-23 09:00:00,ST0358,-2.52,-1.48,1.29,2.67,-1.74,-2.86,5.70
TR_000449604,2101-09-23 10:00:00,ST0358,-2.83,-2.52,-0.13,2.92,-2.51,-2.58,6.61
TR_000576513,2101-09-23 11:00:00,ST0358,-2.77,-2.83,-1.48,2.33,-2.01,-1.90,6.55
TR_000103360,2101-09-23 21:00:00,ST0358,-1.38,0.00,2.84,3.18,-2.52,-1.74,3.70
TR_000408297,2101-09-23 22:00:00,ST0358,-1.31,-1.38,1.56,3.78,-2.83,-2.51,4.29
TR_000044702,2101-09-23 23:00:00,ST0358,-1.59,-1.31,0.00,3.54,-2.77,-2.01,4.59
TR_000623361,2101-09-24 00:00:00,ST0358,-1.73,-1.59,-1.38,2.84,-1.48,-0.92,4.73
TR_000127576,2101-10-13 00:00:00,ST0358,-2.32,-2.33,-0.99,3.28,-2.27,-2.03,6.13
TR_000177958,2101-10-23 00:00:00,ST0358,-2.88,-2.87,-0.47,2.96,-2.91,-2.89,6.36
TR_000659807,2101-10-23 01:00:00,ST0358,-2.87,-2.88,-1.82,2.26,-2.34,-1.80,6.35
TR_000111024,2101-10-23 11:00:00,ST0358,-2.26,-0.99,1.99,3.23,-2.87,-2.87,5.27
TR_000203384,2101-10-23 12:00:00,ST0358,-2.89,-2.26,0.57,3.48,-2.88,-2.91,6.52
TR_000527439,2101-10-23 13:00:00,ST0358,-2.94,-2.89,-0.99,3.01,-2.87,-2.34,6.57
TR_000616583,2101-11-02 01:00:00,ST0358,-1.48,0.22,3.22,2.72,-1.64,-2.16,3.75
TR_000434128,2101-11-02 02:00:00,ST0358,-2.14,-1.48,1.89,3.91,-2.19,-2.16,6.16
TR_000223984,2101-11-02 03:00:00,ST0358,-2.15,-2.14,0.22,3.89,-2.25,-2.15,6.70
TR_000414119,2101-11-02 04:00:00,ST0358,-2.15,-2.15,-1.48,3.22,-2.29,-1.96,6.70
TR_000244773,2101-11-02 14:00:00,ST0358,-1.86,-0.38,3.11,4.02,-2.14,-2.19,4.99
TR_000725051,2101-11-02 15:00:00,ST0358,-2.18,-1.86,1.49,4.55,-2.15,-2.25,6.27
TR_000506175,2101-11-22 00:00:00,ST0358,-1.38,-0.47,1.39,2.91,-2.03,-1.78,3.27
TR_000311862,2101-11-22 01:00:00,ST0358,-1.78,-1.38,0.45,2.87,-1.41,-1.16,4.01
TR_000172874,2101-12-22 00:00:00,ST0358,-2.06,-1.16,1.89,2.53,-1.51,-2.11,4.94
TR_000743787,2101-12-22 01:00:00,ST0358,-2.07,-2.06,0.48,3.18,-2.03,-2.14,5.78
TR_000292907,2101-12-22 02:00:00,ST0358,-2.05,-2.07,-1.16,2.79,-2.05,-2.22,5.78
TR_000557053,2102-01-01 09:00:00,ST0358,-1.56,-0.42,1.31,2.48,-1.70,-1.84,3.38
TR_000172226,2102-01-01 10:00:00,ST0358,-1.77,-1.56,0.36,2.37,-1.43,-1.52,3.88
TR_000337455,2102-03-02 03:00:00,ST0358,-1.96,-0.57,2.73,4.07,-2.59,-2.78,5.23
TR_000576202,2102-03-02 04:00:00,ST0358,-2.68,-1.96,1.19,4.32,-2.62,-2.77,6.70
TR_000296249,2102-03-02 05:00:00,ST0358,-2.67,-2.68,-0.57,3.91,-2.63,-2.87,6.69
TR_000588830,2102-03-02 06:00:00,ST0358,-2.15,-2.67,-1.96,2.73,-1.27,-1.14,6.17
TR_000068479,2102-03-02 15:00:00,ST0358,-1.45,-0.02,3.00,3.27,-1.96,-2.59,4.31
TR_000266803,2102-03-02 16:00:00,ST0358,-2.59,-1.45,1.60,4.02,-2.68,-2.62,6.41
TR_000204952,2102-03-02 17:00:00,ST0358,-2.62,-2.59,-0.02,3.84,-2.67,-2.63,6.44
TR_000641049,2102-03-02 18:00:00,ST0358,-1.97,-2.62,-1.45,3.00,-2.15,-1.27,5.79
TR_000056946,2102-03-03 03:00:00,ST0358,-1.21,-0.13,3.21,2.86,-1.45,-1.96,3.07
TR_000325807,2102-03-12 00:00:00,ST0358,-1.76,-0.89,1.14,2.33,-1.02,-1.93,4.60
TR_000460242,2102-03-12 01:00:00,ST0358,-2.03,-1.76,0.06,2.32,-1.20,-1.12,5.40
TR_000539431,2102-04-01 00:00:00,ST0358,-2.62,-1.55,2.17,5.26,-0.63,-0.50,7.19
TR_000356322,2102-04-01 01:00:00,ST0358,-2.62,-2.62,0.27,4.99,-2.13,-2.61,7.19
TR_000505944,2102-04-01 02:00:00,ST0358,-2.60,-2.62,-1.55,3.95,-2.45,-1.63,7.17
TR_000145971,2102-05-11 01:00:00,ST0358,-2.02,-1.41,2.10,3.78,-2.01,-1.85,6.41
TR_000392654,2102-05-11 02:00:00,ST0358,-2.02,-2.02,0.27,3.93,-2.00,-2.15,7.10
TR_000547208,2102-06-10 00:00:00,ST0358,-2.14,-2.15,-0.65,2.98,-2.22,-2.18,6.44
TR_000003727,2102-06-10 01:00:00,ST0358,-2.15,-2.14,-1.91,2.23,-1.49,-0.84,6.45
TR_000201674,2102-06-10 11:00:00,ST0358,-1.74,-0.40,2.64,4.09,-2.15,-2.11,5.06
TR_000179205,2102-06-10 12:00:00,ST0358,-2.15,-1.74,1.16,4.30,-2.14,-2.22,5.69
TR_000027096,2102-06-10 13:00:00,ST0358,-2.14,-2.15,-0.40,3.79,-2.15,-1.49,5.68
TR_000510926,2102-06-20 01:00:00,ST0358,-2.61,-1.58,1.58,3.50,-1.82,-2.64,5.97
TR_000548549,2102-06-20 02:00:00,ST0358,-2.62,-2.61,-0.02,3.46,-2.65,-2.65,6.26
TR_000459638,2102-06-20 03:00:00,ST0358,-2.63,-2.62,-1.58,2.63,-2.54,-2.64,6.27
TR_000701996,2102-07-20 00:00:00,ST0358,-2.31,-2.30,0.14,4.29,-2.14,-2.27,6.21
TR_000097120,2102-07-20 01:00:00,ST0358,-2.33,-2.31,-1.57,3.28,-2.12,-1.85,6.23
TR_000045588,2102-07-20 11:00:00,ST0358,-2.11,-1.20,2.02,3.90,-2.30,-2.13,5.85
TR_000613871,2102-07-20 12:00:00,ST0358,-2.14,-2.11,0.44,3.90,-2.31,-2.14,6.17
TR_000352301,2102-07-20 13:00:00,ST0358,-2.12,-2.14,-1.20,3.27,-2.33,-2.12,6.15
TR_000531995,2102-08-29 00:00:00,ST0358,-2.51,-2.49,-0.53,2.23,-1.98,-2.45,5.39
TR_000575958,2102-09-18 00:00:00,ST0358,-2.16,-2.17,-0.80,3.87,-2.11,-2.32,5.98
TR_000083844,2102-09-18 01:00:00,ST0358,-1.92,-2.16,-2.16,2.56,-1.76,-1.33,5.74
TR_000452949,2102-09-18 10:00:00,ST0358,-2.13,-0.87,2.37,3.31,-2.16,-2.10,5.47
TR_000622607,2102-09-18 11:00:00,ST0358,-2.12,-2.13,0.93,3.82,-2.17,-2.11,6.20
TR_000219419,2102-09-18 12:00:00,ST0358,-2.13,-2.12,-0.87,3.45,-2.16,-2.11,6.21
TR_000177980,2102-10-08 00:00:00,ST0358,-1.96,-0.38,3.14,3.71,-1.90,-2.63,5.57
TR_000309923,2102-10-08 01:00:00,ST0358,-2.62,-1.96,1.54,4.38,-2.65,-2.62,7.24
TR_000528492,2102-11-17 02:00:00,ST0358,-1.36,-0.20,2.09,2.88,-1.22,-2.12,3.59
TR_000712200,2102-11-17 03:00:00,ST0358,-2.19,-1.36,0.95,3.15,-1.67,-2.14,5.29
TR_000637431,2102-11-17 04:00:00,ST0358,-2.18,-2.19,-0.20,2.80,-1.83,-1.80,5.41
TR_000539283,2102-11-17 16:00:00,ST0358,-1.30,-0.82,1.04,3.23,-2.18,-1.83,3.53
TR_000090518,2103-01-06 06:00:00,ST0358,-1.11,-0.37,1.70,2.97,-1.80,-0.73,3.18
TR_000595302,2103-01-06 07:00:00,ST0358,-1.35,-1.11,0.68,2.97,-1.30,-0.31,3.42
TR_000366110,2103-01-16 03:00:00,ST0358,-1.69,-1.17,0.70,2.59,-2.73,-2.87,3.80
TR_000666007,2103-01-16 04:00:00,ST0358,-1.63,-1.69,-0.33,2.43,-2.29,-2.17,3.74
TR_000639457,2103-01-26 09:00:00,ST0358,-2.26,-1.31,1.47,2.74,-1.99,-2.64,5.13
TR_000257747,2103-01-26 10:00:00,ST0358,-2.62,-2.26,0.08,2.75,-2.61,-2.65,6.16
TR_000128893,2103-01-26 11:00:00,ST0358,-2.60,-2.62,-1.31,2.30,-2.11,-2.27,6.14
TR_000338965,2103-02-05 03:00:00,ST0358,-1.81,-0.98,1.19,2.44,-2.38,-2.76,4.38
TR_000456612,2103-02-05 04:00:00,ST0358,-2.08,-1.81,-0.05,2.38,-2.23,-2.01,4.65
TR_000394317,2103-02-05 16:00:00,ST0358,-1.95,-1.42,0.65,2.54,-2.08,-2.23,4.32
TR_000145472,2103-02-05 17:00:00,ST0358,-1.87,-1.95,-0.49,2.22,-1.41,-1.44,4.40
TR_000394005,2103-02-06 05:00:00,ST0358,-1.50,-1.20,0.52,2.53,-1.87,-1.41,3.78
TR_000576727,2103-02-06 17:00:00,ST0358,-2.01,-1.46,0.49,2.28,-1.50,-1.87,4.22
TR_000080272,2103-02-06 18:00:00,ST0358,-1.97,-2.01,-0.52,2.06,-1.20,-1.27,4.39
TR_000048290,2103-02-07 06:00:00,ST0358,-1.64,-0.33,0.64,2.42,-1.97,-1.20,3.90
TR_000482545,2103-02-25 06:00:00,ST0358,-1.97,-0.75,2.19,3.88,-2.83,-2.91,4.76
TR_000600833,2103-02-25 07:00:00,ST0358,-2.93,-1.97,0.68,4.02,-2.85,-3.00,6.13
TR_000402699,2103-02-25 08:00:00,ST0358,-2.59,-2.93,-0.75,3.36,-2.56,-2.34,5.79
TR_000252466,2103-02-25 18:00:00,ST0358,-2.35,-1.07,1.79,2.79,-1.97,-2.83,5.56
TR_000415322,2103-02-25 19:00:00,ST0358,-2.84,-2.35,0.52,3.20,-2.93,-2.85,6.63
TR_000606891,2103-02-25 20:00:00,ST0358,-2.85,-2.84,-1.07,2.83,-2.59,-2.56,6.64
TR_000205733,2103-02-26 06:00:00,ST0358,-1.26,0.08,2.85,3.21,-2.35,-1.97,3.30
TR_000220641,2103-02-26 07:00:00,ST0358,-2.39,-1.26,1.54,3.79,-2.84,-2.93,5.33
TR_000651370,2103-02-26 08:00:00,ST0358,-2.86,-2.39,0.08,3.60,-2.85,-2.59,5.81
TR_000645718,2103-02-26 09:00:00,ST0358,-2.12,-2.86,-1.26,2.85,-1.80,-1.58,5.07
TR_000624731,2103-02-26 20:00:00,ST0358,-2.82,-0.58,0.40,2.95,-2.86,-2.85,6.38
TR_000461094,2103-02-26 21:00:00,ST0358,-2.28,-2.82,-0.46,2.51,-2.12,-1.80,5.84
TR_000547127,2103-03-27 06:00:00,ST0358,-2.43,-1.18,1.88,3.40,-2.25,-2.67,5.81
TR_000041910,2103-03-27 07:00:00,ST0358,-2.64,-2.43,0.33,3.46,-2.64,-2.67,6.52
TR_000373870,2103-03-27 08:00:00,ST0358,-2.65,-2.64,-1.18,3.04,-2.16,-1.79,6.53
TR_000197679,2103-04-16 00:00:00,ST0358,-1.15,0.53,3.73,3.84,-2.14,-2.22,3.46
TR_000537827,2103-04-16 01:00:00,ST0358,-2.23,-1.15,2.26,4.69,-2.13,-2.22,5.82
TR_000034118,2103-04-16 02:00:00,ST0358,-2.20,-2.23,0.53,4.56,-2.13,-2.24,5.99
TR_000289489,2103-04-16 03:00:00,ST0358,-2.18,-2.20,-1.15,3.73,-2.14,-1.81,5.97
TR_000613161,2103-04-16 12:00:00,ST0358,-1.83,-0.23,2.85,2.31,-1.15,-2.14,4.32
TR_000566518,2103-04-16 13:00:00,ST0358,-2.14,-1.83,1.54,3.59,-2.23,-2.13,6.18
TR_000375918,2103-04-16 14:00:00,ST0358,-2.14,-2.14,-0.23,3.79,-2.20,-2.13,6.80
TR_000295590,2103-04-16 15:00:00,ST0358,-2.13,-2.14,-1.83,2.85,-2.18,-2.14,6.79
TR_000325294,2103-05-06 08:00:00,ST0358,-0.28,-0.08,3.43,3.83,-2.61,-1.81,2.82

Train | ST0292 | 210개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000492897,2100-01-21 09:00:00,ST0292,-2.72,-2.02,-0.28,2.08,-2.81,-3.02,4.89
TR_000556269,2100-01-31 23:00:00,ST0292,-3.33,-2.82,-1.53,0.71,-2.89,-2.68,4.87
TR_000058289,2100-02-01 11:00:00,ST0292,-2.54,-1.91,-0.29,1.54,-3.33,-2.89,3.12
TR_000702356,2100-02-01 12:00:00,ST0292,-3.07,-2.54,-1.14,1.44,-3.57,-2.62,4.10
TR_000673169,2100-02-20 00:00:00,ST0292,-3.03,-2.42,-0.78,2.30,-3.59,-3.32,4.75
TR_000054371,2100-02-20 01:00:00,ST0292,-3.08,-3.03,-1.67,1.31,-3.17,-2.84,4.80
TR_000100855,2100-03-02 07:00:00,ST0292,-2.58,-1.88,-0.17,1.79,-3.23,-2.93,3.52
TR_000040190,2100-03-02 08:00:00,ST0292,-3.13,-2.58,-1.09,1.61,-3.71,-3.40,4.07
TR_000718422,2100-04-01 00:00:00,ST0292,-2.85,-2.28,-0.79,1.99,-3.37,-3.22,4.27
TR_000476450,2100-04-01 12:00:00,ST0292,-3.12,-2.54,-1.13,1.42,-2.85,-3.37,4.79
TR_000213393,2100-04-02 00:00:00,ST0292,-2.51,-1.91,-0.40,1.67,-3.12,-2.85,3.44
TR_000469922,2100-04-02 01:00:00,ST0292,-2.95,-2.51,-1.22,1.26,-3.16,-2.79,3.88
TR_000525822,2100-04-02 13:00:00,ST0292,-3.34,-2.86,-1.62,0.67,-2.95,-3.16,4.43
TR_000228294,2100-04-11 03:00:00,ST0292,-2.38,-1.74,-0.03,2.18,-3.00,-2.65,4.14
TR_000464037,2100-04-11 04:00:00,ST0292,-2.89,-2.38,-0.98,1.80,-3.35,-2.89,4.65
TR_000617236,2100-05-31 03:00:00,ST0292,-3.19,-2.67,-1.31,1.02,-3.35,-3.07,4.75
TR_000269377,2100-06-10 00:00:00,ST0292,-3.52,-3.06,-1.78,0.91,-2.95,-2.20,6.09
TR_000391084,2100-06-30 06:00:00,ST0292,-3.42,-2.81,-1.36,1.35,-2.94,-3.71,5.93
TR_000587495,2100-06-30 07:00:00,ST0292,-3.76,-3.42,-2.12,0.54,-3.24,-3.17,6.27
TR_000286318,2100-06-30 18:00:00,ST0292,-2.29,-1.63,0.08,2.51,-3.42,-2.94,2.93
TR_000735731,2100-06-30 19:00:00,ST0292,-2.76,-2.29,-0.85,2.00,-3.76,-3.24,3.40
TR_000527122,2100-07-10 00:00:00,ST0292,-2.91,-2.31,-0.63,2.32,-2.82,-3.38,5.94
TR_000103286,2100-07-10 01:00:00,ST0292,-3.45,-2.91,-1.56,1.69,-3.36,-3.74,6.48
TR_000540648,2100-07-30 06:00:00,ST0292,-2.23,-1.38,0.95,1.90,-2.54,-2.52,3.17
TR_000240356,2100-07-30 07:00:00,ST0292,-2.91,-2.23,-0.30,2.84,-3.16,-3.11,5.13
TR_000124916,2100-08-09 02:00:00,ST0292,-2.16,-1.41,0.58,2.63,-2.78,-2.60,3.74
TR_000495766,2100-08-09 03:00:00,ST0292,-2.80,-2.16,-0.49,2.67,-3.35,-3.17,4.72
TR_000424488,2100-08-09 04:00:00,ST0292,-3.23,-2.80,-1.41,1.73,-3.28,-2.92,5.15
TR_000002265,2100-08-09 14:00:00,ST0292,-2.50,-1.79,0.04,1.58,-2.16,-2.78,4.08
TR_000482689,2100-08-09 15:00:00,ST0292,-3.12,-2.50,-0.94,1.92,-2.80,-3.35,5.54
TR_000579957,2100-08-09 16:00:00,ST0292,-3.59,-3.12,-1.79,1.11,-3.23,-3.28,6.01
TR_000286580,2100-08-19 00:00:00,ST0292,-3.56,-3.22,-1.86,1.42,-3.15,-2.67,6.38
TR_000740687,2100-08-19 10:00:00,ST0292,-2.36,-1.54,0.66,2.54,-2.61,-2.82,4.32
TR_000127249,2100-08-19 11:00:00,ST0292,-3.00,-2.36,-0.48,2.82,-3.22,-3.40,5.60
TR_000018909,2100-08-19 12:00:00,ST0292,-3.48,-3.00,-1.54,1.85,-3.56,-3.15,6.08
TR_000592188,2100-09-08 06:00:00,ST0292,-2.50,-1.81,0.20,3.10,-2.69,-2.78,5.32
TR_000340712,2100-09-08 07:00:00,ST0292,-3.11,-2.50,-0.93,2.65,-3.28,-3.34,5.99
TR_000410486,2100-09-08 08:00:00,ST0292,-3.36,-3.11,-1.81,1.43,-3.09,-2.46,6.24
TR_000180720,2100-09-08 18:00:00,ST0292,-2.28,-1.55,0.57,2.82,-2.50,-2.69,4.49
TR_000369913,2100-09-08 19:00:00,ST0292,-2.91,-2.28,-0.59,2.88,-3.11,-3.28,5.58
TR_000580589,2100-09-08 20:00:00,ST0292,-3.43,-2.91,-1.55,1.82,-3.36,-3.09,6.10
TR_000278920,2100-09-18 00:00:00,ST0292,-2.97,-2.43,-1.00,2.01,-3.25,-2.59,4.98
TR_000141581,2100-10-08 02:00:00,ST0292,-2.70,-2.18,-0.75,1.34,-3.18,-2.64,3.90
TR_000031038,2100-10-08 14:00:00,ST0292,-2.84,-2.24,-0.74,1.20,-2.70,-3.18,4.04
TR_000705687,2100-10-08 15:00:00,ST0292,-3.33,-2.84,-1.53,0.87,-2.89,-2.84,5.13
TR_000210556,2100-10-18 00:00:00,ST0292,-3.43,-2.90,-1.49,1.90,-3.09,-3.15,7.25
TR_000341899,2100-11-07 06:00:00,ST0292,-2.78,-2.15,-0.54,1.51,-2.52,-3.33,4.46
TR_000337715,2100-11-07 07:00:00,ST0292,-3.29,-2.78,-1.40,1.22,-2.89,-3.23,5.71
TR_000502938,2100-12-07 08:00:00,ST0292,-2.11,-1.36,0.75,2.83,-2.42,-2.47,4.25
TR_000467746,2100-12-07 09:00:00,ST0292,-2.74,-2.11,-0.42,3.01,-3.00,-3.03,5.68
TR_000187748,2100-12-07 10:00:00,ST0292,-3.28,-2.74,-1.36,2.04,-3.46,-3.12,6.22
TR_000410718,2100-12-07 20:00:00,ST0292,-1.89,-1.11,1.05,2.14,-2.11,-2.42,3.47
TR_000490338,2100-12-07 21:00:00,ST0292,-2.55,-1.89,-0.10,2.94,-2.74,-3.00,5.29
TR_000330924,2100-12-07 22:00:00,ST0292,-3.13,-2.55,-1.11,2.23,-3.28,-3.46,5.87
TR_000453367,2100-12-08 09:00:00,ST0292,-2.45,-1.76,0.11,2.74,-2.55,-2.74,4.86
TR_000207728,2100-12-08 10:00:00,ST0292,-3.02,-2.45,-0.94,2.36,-3.13,-3.28,5.62
TR_000566642,2100-12-08 11:00:00,ST0292,-3.24,-3.02,-1.76,1.24,-2.91,-2.64,5.84
TR_000692454,2100-12-08 21:00:00,ST0292,-2.12,-1.39,0.56,2.41,-2.45,-2.55,3.87
TR_000272232,2100-12-08 22:00:00,ST0292,-2.73,-2.12,-0.50,2.60,-3.02,-3.13,4.89
TR_000565565,2100-12-08 23:00:00,ST0292,-3.17,-2.73,-1.39,1.66,-3.24,-2.91,5.33
TR_000719021,2100-12-09 10:00:00,ST0292,-2.80,-2.19,-0.58,2.16,-2.73,-3.02,4.86
TR_000504127,2100-12-09 11:00:00,ST0292,-3.29,-2.80,-1.46,1.45,-3.17,-3.24,5.35
TR_000486313,2100-12-27 06:00:00,ST0292,-1.77,-1.00,1.22,3.04,-2.95,-2.67,3.70
TR_000058720,2100-12-27 07:00:00,ST0292,-2.40,-1.77,0.02,3.22,-3.44,-3.16,4.92
TR_000375232,2100-12-27 08:00:00,ST0292,-2.88,-2.40,-1.00,2.35,-3.23,-2.55,5.40
TR_000568123,2101-02-05 00:00:00,ST0292,-3.25,-2.74,-1.27,2.15,-3.32,-2.61,5.54
TR_000072007,2101-02-15 00:00:00,ST0292,-2.33,-1.52,0.68,2.16,-2.46,-2.74,4.26
TR_000595773,2101-02-15 01:00:00,ST0292,-3.02,-2.33,-0.49,2.78,-3.10,-3.35,6.16
TR_000305735,2101-02-15 02:00:00,ST0292,-3.55,-3.02,-1.52,1.91,-3.62,-3.71,6.69
TR_000300883,2101-03-07 05:00:00,ST0292,-2.13,-1.39,0.74,3.12,-2.25,-2.49,5.05
TR_000731580,2101-03-07 06:00:00,ST0292,-2.75,-2.13,-0.46,3.13,-2.86,-3.08,6.33
TR_000197941,2101-03-07 07:00:00,ST0292,-3.30,-2.75,-1.39,2.03,-3.33,-3.01,6.88
TR_000206413,2101-03-07 17:00:00,ST0292,-1.73,-0.93,1.41,2.92,-2.13,-2.25,4.00
TR_000497371,2101-03-07 18:00:00,ST0292,-2.39,-1.73,0.14,3.58,-2.75,-2.86,5.70
TR_000271684,2101-03-07 19:00:00,ST0292,-2.97,-2.39,-0.93,2.72,-3.30,-3.33,6.28
TR_000444535,2101-03-07 20:00:00,ST0292,-2.67,-2.97,-1.73,1.41,-2.51,-2.19,5.98
TR_000164024,2101-03-08 06:00:00,ST0292,-2.41,-1.72,0.20,3.31,-2.39,-2.75,5.19
TR_000585467,2101-03-08 07:00:00,ST0292,-2.99,-2.41,-0.88,2.71,-2.97,-3.30,5.80
TR_000663773,2101-03-08 08:00:00,ST0292,-3.30,-2.99,-1.72,1.47,-2.67,-2.51,6.11
TR_000633604,2101-03-08 18:00:00,ST0292,-2.21,-1.47,0.57,2.78,-2.41,-2.39,3.99
TR_000141064,2101-03-08 19:00:00,ST0292,-2.83,-2.21,-0.57,2.81,-2.99,-2.97,5.02
TR_000033683,2101-03-08 20:00:00,ST0292,-3.35,-2.83,-1.47,1.81,-3.30,-2.67,5.54
TR_000741789,2101-03-17 01:00:00,ST0292,-2.38,-1.75,-0.05,1.98,-3.32,-2.85,3.11
TR_000268713,2101-03-17 02:00:00,ST0292,-2.90,-2.38,-0.96,1.69,-3.52,-3.01,3.89
TR_000413368,2101-04-16 07:00:00,ST0292,-2.48,-1.81,-0.12,1.76,-2.56,-2.80,4.15
TR_000177974,2101-04-16 08:00:00,ST0292,-3.06,-2.48,-1.03,1.77,-3.12,-3.30,4.88
TR_000719816,2101-05-16 06:00:00,ST0292,-2.74,-2.10,-0.46,1.93,-3.52,-3.20,3.53
TR_000203433,2101-06-05 07:00:00,ST0292,-3.23,-2.64,-1.20,1.54,-2.79,-3.55,5.84
TR_000242530,2101-06-05 08:00:00,ST0292,-3.55,-3.23,-1.98,0.73,-3.10,-2.93,6.16
TR_000550130,2101-07-05 07:00:00,ST0292,-2.22,-1.47,0.56,2.08,-2.28,-2.67,4.37
TR_000084777,2101-07-05 08:00:00,ST0292,-2.81,-2.22,-0.51,2.60,-2.89,-3.22,5.98
TR_000701967,2101-08-04 01:00:00,ST0292,-2.93,-2.39,-1.05,1.12,-3.01,-3.23,4.22
TR_000442003,2101-08-04 13:00:00,ST0292,-2.73,-2.18,-0.81,1.29,-2.93,-3.01,3.52
TR_000334364,2101-09-03 00:00:00,ST0292,-3.17,-2.58,-1.09,2.11,-3.16,-3.38,5.90
TR_000103058,2101-09-03 01:00:00,ST0292,-3.33,-3.17,-1.91,1.03,-2.87,-2.48,6.06
TR_000313755,2101-09-23 00:00:00,ST0292,-3.15,-2.73,-1.30,1.47,-3.26,-2.71,4.65
TR_000399338,2101-09-23 11:00:00,ST0292,-3.07,-2.42,-0.78,1.50,-2.73,-3.51,5.22
TR_000022516,2101-09-23 12:00:00,ST0292,-3.58,-3.07,-1.68,1.05,-3.15,-3.26,5.85
TR_000067379,2101-09-23 23:00:00,ST0292,-2.16,-1.42,0.50,2.15,-3.07,-2.73,3.46
TR_000666422,2101-09-24 00:00:00,ST0292,-2.78,-2.16,-0.51,2.27,-3.58,-3.15,4.39
TR_000247161,2101-09-24 01:00:00,ST0292,-3.12,-2.78,-1.42,1.46,-3.10,-2.56,4.73
TR_000385604,2101-10-13 00:00:00,ST0292,-2.67,-2.02,-0.35,2.14,-2.97,-3.07,4.70
TR_000058817,2101-10-13 01:00:00,ST0292,-3.23,-2.67,-1.24,1.65,-3.42,-3.33,5.26
TR_000678518,2101-10-23 01:00:00,ST0292,-3.17,-2.56,-0.98,1.58,-3.28,-3.58,5.05
TR_000274229,2101-10-23 02:00:00,ST0292,-3.66,-3.17,-1.83,0.93,-3.49,-3.27,5.54
TR_000036012,2101-10-23 13:00:00,ST0292,-2.74,-2.04,-0.31,1.88,-3.17,-3.28,4.52
TR_000303840,2101-10-23 14:00:00,ST0292,-3.32,-2.74,-1.23,1.64,-3.66,-3.49,5.13
TR_000407839,2101-11-02 04:00:00,ST0292,-2.70,-2.02,-0.30,2.25,-2.82,-3.19,5.19
TR_000016776,2101-11-02 05:00:00,ST0292,-3.26,-2.70,-1.24,1.81,-3.33,-3.38,5.91
TR_000233040,2101-12-02 00:00:00,ST0292,-3.14,-2.58,-1.00,2.38,-3.72,-2.95,5.37
TR_000609190,2101-12-22 03:00:00,ST0292,-3.39,-2.76,-1.29,1.26,-2.82,-3.61,5.44
TR_000552387,2101-12-22 04:00:00,ST0292,-3.79,-3.39,-2.06,0.58,-3.25,-3.29,5.84
TR_000646373,2102-03-02 05:00:00,ST0292,-2.51,-1.79,0.19,2.60,-2.84,-2.83,4.50
TR_000201499,2102-03-02 06:00:00,ST0292,-3.10,-2.51,-0.87,2.32,-3.37,-3.33,5.41
TR_000746522,2102-03-02 07:00:00,ST0292,-3.28,-3.10,-1.79,1.29,-2.77,-2.56,5.59
TR_000265077,2102-03-02 17:00:00,ST0292,-2.43,-1.65,0.32,1.99,-2.51,-2.84,4.07
TR_000545550,2102-03-02 18:00:00,ST0292,-3.04,-2.43,-0.70,2.31,-3.10,-3.37,5.27
TR_000228313,2102-03-02 19:00:00,ST0292,-3.37,-3.04,-1.65,1.44,-3.28,-2.77,5.60
TR_000458111,2102-04-01 01:00:00,ST0292,-1.88,-1.11,1.24,3.51,-2.58,-2.45,4.53
TR_000576720,2102-04-01 02:00:00,ST0292,-2.49,-1.88,-0.09,3.54,-3.14,-3.00,5.55
TR_000380799,2102-04-01 03:00:00,ST0292,-2.97,-2.49,-1.11,2.49,-3.33,-2.75,6.03
TR_000141473,2102-06-10 01:00:00,ST0292,-3.07,-2.48,-0.98,1.70,-2.61,-3.39,5.69
TR_000077847,2102-06-10 02:00:00,ST0292,-3.44,-3.07,-1.79,0.95,-2.91,-2.76,6.06
TR_000619753,2102-06-10 13:00:00,ST0292,-2.30,-1.63,0.22,2.62,-3.07,-2.61,4.09
TR_000456962,2102-06-10 14:00:00,ST0292,-2.85,-2.30,-0.80,2.26,-3.44,-2.91,4.64
TR_000099040,2102-06-20 03:00:00,ST0292,-3.03,-2.41,-0.78,1.64,-2.76,-3.31,4.61
TR_000141954,2102-06-20 04:00:00,ST0292,-3.56,-3.03,-1.67,1.20,-3.30,-3.74,5.15
TR_000435115,2102-07-20 00:00:00,ST0292,-2.04,-1.28,0.78,2.47,-2.51,-2.37,3.42
TR_000512049,2102-07-20 01:00:00,ST0292,-2.69,-2.04,-0.35,2.86,-3.11,-2.94,4.98
TR_000394113,2102-07-20 02:00:00,ST0292,-3.21,-2.69,-1.28,1.98,-3.43,-3.00,5.50
TR_000600830,2102-07-20 13:00:00,ST0292,-2.65,-1.98,-0.24,2.29,-2.69,-3.11,4.87
TR_000626884,2102-07-20 14:00:00,ST0292,-3.21,-2.65,-1.20,1.89,-3.21,-3.43,5.43
TR_000663022,2102-08-19 08:00:00,ST0292,-2.68,-1.98,-0.18,1.43,-2.68,-2.98,3.26
TR_000073301,2102-08-19 09:00:00,ST0292,-3.29,-2.68,-1.15,1.65,-3.27,-3.55,4.59
TR_000737624,2102-08-19 10:00:00,ST0292,-3.75,-3.29,-1.98,0.85,-3.44,-3.35,5.05
TR_000466765,2102-08-29 01:00:00,ST0292,-3.39,-2.87,-1.53,0.67,-2.86,-3.50,4.70
TR_000702248,2102-09-18 00:00:00,ST0292,-2.42,-1.68,0.18,2.45,-2.83,-2.75,4.18
TR_000322451,2102-09-18 01:00:00,ST0292,-3.02,-2.42,-0.83,2.31,-3.40,-3.29,5.01
TR_000507968,2102-09-18 02:00:00,ST0292,-3.14,-3.02,-1.68,1.28,-3.15,-2.74,5.13
TR_000230428,2102-09-18 12:00:00,ST0292,-2.54,-1.83,-0.02,1.76,-2.42,-2.83,4.27
TR_000709824,2102-11-17 05:00:00,ST0292,-3.07,-2.50,-1.07,1.39,-2.81,-3.29,4.64
TR_000004473,2102-11-17 06:00:00,ST0292,-3.30,-3.07,-1.83,0.72,-2.68,-2.88,4.87
TR_000593718,2102-11-17 18:00:00,ST0292,-2.69,-2.34,-1.04,1.34,-3.30,-2.68,3.44
TR_000592661,2103-01-26 00:00:00,ST0292,-3.29,-2.82,-1.41,1.49,-3.63,-2.96,4.33
TR_000383701,2103-01-26 11:00:00,ST0292,-3.11,-2.52,-1.01,1.04,-2.82,-3.41,4.51
TR_000325399,2103-01-26 12:00:00,ST0292,-3.58,-3.11,-1.83,0.71,-3.29,-3.63,5.33
TR_000722985,2103-02-05 05:00:00,ST0292,-3.02,-2.47,-1.05,1.02,-3.22,-3.42,4.23
TR_000320094,2103-02-25 08:00:00,ST0292,-2.57,-1.90,-0.05,2.62,-3.15,-2.77,4.32
TR_000296126,2103-02-25 09:00:00,ST0292,-3.10,-2.57,-1.06,2.05,-3.55,-3.14,4.85
TR_000400137,2103-02-25 20:00:00,ST0292,-2.81,-2.13,-0.34,1.75,-2.57,-3.15,5.01
TR_000677959,2103-02-25 21:00:00,ST0292,-3.36,-2.81,-1.33,1.58,-3.10,-3.55,5.70
TR_000255287,2103-02-26 08:00:00,ST0292,-2.20,-1.44,0.50,2.20,-2.81,-2.57,3.26
TR_000667687,2103-02-26 09:00:00,ST0292,-2.80,-2.20,-0.54,2.34,-3.36,-3.10,4.49
TR_000520127,2103-02-26 10:00:00,ST0292,-3.20,-2.80,-1.44,1.54,-3.14,-2.88,4.89
TR_000222364,2103-02-26 21:00:00,ST0292,-2.85,-2.26,-0.63,1.69,-2.80,-3.36,4.98
TR_000680699,2103-02-26 22:00:00,ST0292,-3.24,-2.85,-1.52,1.25,-3.20,-3.14,5.37
TR_000298229,2103-03-27 08:00:00,ST0292,-2.86,-2.21,-0.55,1.79,-2.95,-3.48,4.69
TR_000582111,2103-03-27 09:00:00,ST0292,-3.42,-2.86,-1.46,1.37,-3.39,-3.32,5.25
TR_000664828,2103-04-16 02:00:00,ST0292,-1.79,-0.98,1.12,2.35,-2.70,-2.30,2.69
TR_000141585,2103-04-16 03:00:00,ST0292,-2.47,-1.79,0.03,2.99,-3.29,-2.90,4.34
TR_000260004,2103-04-16 04:00:00,ST0292,-3.01,-2.47,-0.98,2.25,-3.65,-3.09,4.88
TR_000593353,2103-04-16 15:00:00,ST0292,-2.93,-2.27,-0.63,1.87,-2.47,-3.29,5.43
TR_000259206,2103-04-16 16:00:00,ST0292,-3.47,-2.93,-1.53,1.48,-3.01,-3.65,6.09
TR_000586494,2103-05-06 10:00:00,ST0292,-2.06,-1.31,0.73,2.54,-3.11,-2.81,3.64
TR_000025572,2103-05-06 11:00:00,ST0292,-2.66,-2.06,-0.35,2.56,-3.56,-3.03,4.82
TR_000161935,2103-05-06 12:00:00,ST0292,-3.01,-2.66,-1.31,1.74,-2.86,-2.26,5.17
TR_000213868,2103-05-06 23:00:00,ST0292,-2.84,-2.28,-0.60,2.16,-2.66,-3.56,6.14
TR_000209964,2103-05-07 00:00:00,ST0292,-3.26,-2.84,-1.56,1.43,-3.01,-2.86,6.56
TR_000480990,2103-05-07 11:00:00,ST0292,-1.96,-1.19,0.82,3.30,-2.84,-2.66,4.35
TR_000232274,2103-05-07 12:00:00,ST0292,-2.56,-1.96,-0.31,2.99,-3.26,-3.01,5.19
TR_000192779,2103-05-07 13:00:00,ST0292,-2.90,-2.56,-1.19,2.02,-2.57,-2.20,5.53
TR_000288653,2103-05-26 00:00:00,ST0292,-2.50,-1.87,-0.24,1.59,-2.47,-2.91,3.66
TR_000548353,2103-05-26 01:00:00,ST0292,-3.04,-2.50,-1.09,1.45,-2.94,-3.31,4.83
TR_000615294,2103-05-26 13:00:00,ST0292,-2.31,-1.72,-0.13,1.79,-3.04,-2.94,3.22
TR_000040961,2103-05-26 14:00:00,ST0292,-2.71,-2.31,-0.98,1.46,-3.09,-2.48,3.62
TR_000076116,2103-06-05 09:00:00,ST0292,-2.47,-1.78,0.05,1.59,-2.17,-2.93,4.31
TR_000273839,2103-06-05 10:00:00,ST0292,-3.08,-2.47,-0.92,1.85,-2.77,-3.46,5.77
TR_000188044,2103-06-05 11:00:00,ST0292,-3.53,-3.08,-1.78,1.08,-3.10,-3.10,6.22
TR_000403175,2103-06-05 22:00:00,ST0292,-2.46,-1.77,0.10,2.69,-3.08,-2.77,4.44
TR_000326728,2103-06-05 23:00:00,ST0292,-3.01,-2.46,-0.93,2.21,-3.53,-3.10,4.99
TR_000013358,2103-06-06 10:00:00,ST0292,-2.74,-2.06,-0.30,1.98,-2.46,-3.08,5.33
TR_000740472,2103-06-06 11:00:00,ST0292,-3.31,-2.74,-1.26,1.72,-3.01,-3.53,6.08
TR_000597358,2103-06-06 22:00:00,ST0292,-2.09,-1.33,0.76,2.59,-2.74,-2.46,3.86
TR_000713888,2103-06-06 23:00:00,ST0292,-2.71,-2.09,-0.34,2.77,-3.31,-3.01,5.11
TR_000283908,2103-06-07 00:00:00,ST0292,-3.20,-2.71,-1.33,1.92,-3.18,-2.74,5.60
TR_000680578,2103-06-07 10:00:00,ST0292,-2.24,-1.50,0.52,1.77,-2.09,-2.74,4.15
TR_000683624,2103-06-07 11:00:00,ST0292,-2.87,-2.24,-0.54,2.40,-2.71,-3.31,5.78
TR_000100401,2103-06-07 12:00:00,ST0292,-3.38,-2.87,-1.50,1.65,-3.20,-3.18,6.29
TR_000232083,2103-06-07 23:00:00,ST0292,-2.38,-1.71,0.23,2.91,-2.87,-2.71,4.84
TR_000067640,2103-06-08 00:00:00,ST0292,-2.94,-2.38,-0.87,2.49,-3.38,-3.20,5.40
TR_000081729,2103-06-08 01:00:00,ST0292,-2.98,-2.94,-1.71,1.36,-2.62,-2.33,5.44
TR_000293812,2103-06-08 11:00:00,ST0292,-2.02,-1.48,0.24,2.46,-2.38,-2.87,5.12
TR_000067507,2103-06-08 12:00:00,ST0292,-2.52,-2.02,-0.77,2.37,-2.94,-3.38,5.71
TR_000124369,2103-06-08 13:00:00,ST0292,-2.74,-2.52,-1.48,1.35,-2.98,-2.62,5.93
TR_000702137,2103-06-08 23:00:00,ST0292,-1.66,-0.94,1.12,3.10,-2.02,-2.38,4.60
TR_000463658,2103-06-09 00:00:00,ST0292,-2.21,-1.66,-0.03,3.19,-2.52,-2.94,5.23
TR_000264831,2103-06-09 01:00:00,ST0292,-2.56,-2.21,-0.94,2.29,-2.74,-2.98,5.58
TR_000737795,2103-06-09 11:00:00,ST0292,-1.46,-0.81,1.11,2.94,-1.66,-2.02,4.34
TR_000435122,2103-06-09 12:00:00,ST0292,-1.97,-1.46,-0.03,3.02,-2.21,-2.52,5.31
TR_000401664,2103-06-09 13:00:00,ST0292,-2.32,-1.97,-0.81,2.27,-2.56,-2.74,5.66
TR_000075677,2103-06-09 23:00:00,ST0292,-1.69,-0.88,1.54,2.88,-1.46,-1.66,3.42
TR_000408561,2103-06-10 00:00:00,ST0292,-2.30,-1.69,0.14,3.34,-1.97,-2.21,5.08
TR_000075764,2103-06-10 01:00:00,ST0292,-2.76,-2.30,-0.88,2.68,-2.32,-2.56,5.54
TR_000291558,2103-06-10 02:00:00,ST0292,-2.79,-2.76,-1.69,1.54,-1.82,-1.51,5.57
TR_000021929,2103-06-10 12:00:00,ST0292,-2.49,-1.80,0.31,2.78,-2.30,-1.97,5.10
TR_000335088,2103-06-10 13:00:00,ST0292,-3.04,-2.49,-0.89,2.54,-2.76,-2.32,5.76
TR_000241440,2103-06-10 14:00:00,ST0292,-3.26,-3.04,-1.80,1.50,-2.79,-1.82,5.98
TR_000196049,2103-06-11 00:00:00,ST0292,-2.26,-1.53,0.64,2.61,-2.49,-2.30,4.30
TR_000224564,2103-06-11 01:00:00,ST0292,-2.87,-2.26,-0.56,2.72,-3.04,-2.76,5.50
TR_000092752,2103-06-11 02:00:00,ST0292,-3.31,-2.87,-1.53,1.77,-3.26,-2.79,5.94

Train | ST0326 | 198개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000116918,2100-01-01 01:00:00,ST0326,-2.36,-1.94,-0.40,1.95,-1.94,-2.56,4.95
TR_000308142,2100-01-21 06:00:00,ST0326,-2.64,-1.82,0.56,2.74,-2.77,-2.98,5.41
TR_000188065,2100-01-21 07:00:00,ST0326,-3.06,-2.64,-0.85,2.67,-3.21,-3.18,5.84
TR_000199387,2100-01-21 08:00:00,ST0326,-2.61,-3.06,-1.82,1.83,-2.62,-2.22,5.39
TR_000340984,2100-02-01 10:00:00,ST0326,-2.49,-0.66,-0.15,1.71,-1.85,-0.87,4.39
TR_000443877,2100-03-02 05:00:00,ST0326,-2.16,-0.90,0.31,2.42,-2.76,-2.40,4.00
TR_000166341,2100-04-01 09:00:00,ST0326,-2.10,-1.67,-0.06,2.32,-1.82,-2.60,4.47
TR_000651757,2100-04-11 00:00:00,ST0326,-1.56,-0.98,1.27,2.72,-2.20,-1.66,3.82
TR_000023476,2100-04-11 01:00:00,ST0326,-2.16,-1.56,0.07,2.66,-2.40,-1.70,4.49
TR_000287732,2100-04-21 00:00:00,ST0326,-1.96,-1.27,1.44,2.09,-1.42,-2.41,4.16
TR_000131132,2100-05-01 04:00:00,ST0326,-1.84,-1.28,0.40,2.43,-2.30,-1.39,4.12
TR_000741295,2100-06-30 02:00:00,ST0326,-2.48,-1.88,0.46,2.12,-1.93,-3.15,4.87
TR_000439231,2100-06-30 03:00:00,ST0326,-3.15,-2.48,-0.80,2.12,-2.46,-3.16,6.38
TR_000557206,2100-06-30 04:00:00,ST0326,-2.86,-3.15,-1.88,1.52,-2.27,-2.37,6.09
TR_000403396,2100-06-30 15:00:00,ST0326,-1.54,-0.94,1.33,3.23,-3.15,-2.46,3.45
TR_000091004,2100-06-30 16:00:00,ST0326,-1.67,-1.54,0.13,2.90,-2.86,-2.27,3.69
TR_000594591,2100-07-30 03:00:00,ST0326,-2.21,-1.22,1.93,2.87,-2.81,-2.64,4.74
TR_000200739,2100-07-30 04:00:00,ST0326,-2.41,-2.21,0.89,3.16,-3.66,-3.40,5.35
TR_000096547,2100-07-30 05:00:00,ST0326,-3.74,-2.41,-1.22,2.92,-3.91,-3.41,6.68
TR_000703491,2100-07-30 06:00:00,ST0326,-3.10,-3.74,-2.21,1.93,-3.02,-2.02,6.04
TR_000749574,2100-08-09 00:00:00,ST0326,-2.87,-1.33,0.37,3.37,-3.58,-3.32,5.51
TR_000627284,2100-08-09 01:00:00,ST0326,-2.79,-2.87,-0.74,2.72,-3.02,-2.64,5.43
TR_000724785,2100-08-09 11:00:00,ST0326,-2.36,-1.51,1.04,2.35,-1.33,-3.11,4.81
TR_000044610,2100-08-09 12:00:00,ST0326,-3.14,-2.36,-0.42,2.64,-2.87,-3.58,6.14
TR_000090715,2100-08-09 13:00:00,ST0326,-3.12,-3.14,-1.51,2.08,-2.79,-3.02,6.12
TR_000557380,2100-08-19 08:00:00,ST0326,-1.07,-0.76,0.62,3.36,-3.34,-3.43,4.04
TR_000608690,2100-08-19 09:00:00,ST0326,-1.30,-1.07,-0.26,2.74,-3.26,-2.95,4.29
TR_000570912,2100-08-19 10:00:00,ST0326,-2.68,-1.30,-0.76,1.70,-1.95,-1.30,5.67
TR_000028755,2100-08-29 01:00:00,ST0326,-2.22,-1.38,0.83,2.04,-1.57,-2.49,4.57
TR_000113350,2100-08-29 02:00:00,ST0326,-2.80,-2.22,-0.29,2.43,-2.25,-2.65,5.75
TR_000044914,2100-09-08 03:00:00,ST0326,-2.07,-0.90,1.17,3.54,-3.04,-3.26,5.43
TR_000680364,2100-09-08 04:00:00,ST0326,-3.29,-2.07,0.21,3.35,-3.56,-3.53,6.86
TR_000444405,2100-09-08 05:00:00,ST0326,-3.37,-3.29,-0.90,2.32,-3.08,-2.59,6.94
TR_000108567,2100-09-08 15:00:00,ST0326,-2.16,-1.36,1.61,3.36,-2.07,-3.04,4.86
TR_000429054,2100-09-08 16:00:00,ST0326,-2.98,-2.16,0.02,3.57,-3.29,-3.56,6.21
TR_000396332,2100-09-08 17:00:00,ST0326,-3.11,-2.98,-1.36,2.84,-3.37,-3.08,6.34
TR_000156297,2100-10-08 12:00:00,ST0326,-2.48,-1.25,0.11,1.77,-1.37,-1.62,4.72
TR_000107687,2100-10-28 00:00:00,ST0326,-2.19,-1.45,1.00,2.10,-1.55,-2.85,4.77
TR_000227824,2100-11-07 03:00:00,ST0326,-2.20,-1.45,0.83,2.00,-1.34,-2.48,4.54
TR_000484530,2100-11-07 04:00:00,ST0326,-2.30,-2.20,0.13,2.01,-1.61,-2.31,5.16
TR_000525186,2100-11-07 05:00:00,ST0326,-2.75,-2.30,-1.45,1.47,-1.45,-1.36,5.61
TR_000122256,2100-11-07 16:00:00,ST0326,-1.62,-0.83,1.22,2.86,-2.30,-1.61,3.80
TR_000691126,2100-12-07 05:00:00,ST0326,-2.42,-1.54,1.62,3.47,-2.96,-3.06,5.41
TR_000465928,2100-12-07 06:00:00,ST0326,-3.30,-2.42,0.03,3.65,-3.69,-3.90,6.80
TR_000011306,2100-12-07 07:00:00,ST0326,-3.46,-3.30,-1.54,2.89,-3.44,-3.01,6.96
TR_000005944,2100-12-07 08:00:00,ST0326,-2.61,-3.46,-2.42,1.62,-1.95,-1.14,6.11
TR_000339710,2100-12-07 17:00:00,ST0326,-1.90,-0.99,2.09,2.99,-2.42,-2.96,4.54
TR_000068897,2100-12-07 18:00:00,ST0326,-2.80,-1.90,0.66,3.50,-3.30,-3.69,6.04
TR_000307628,2100-12-07 19:00:00,ST0326,-3.30,-2.80,-0.99,3.02,-3.46,-3.44,6.54
TR_000133172,2100-12-07 20:00:00,ST0326,-2.69,-3.30,-1.90,2.09,-2.61,-1.95,5.93
TR_000045488,2100-12-08 06:00:00,ST0326,-2.82,-1.06,1.13,3.24,-2.80,-3.30,5.87
TR_000176433,2100-12-08 07:00:00,ST0326,-3.21,-2.82,0.08,3.19,-3.30,-3.46,6.63
TR_000458082,2100-12-08 08:00:00,ST0326,-2.65,-3.21,-1.06,2.20,-2.69,-2.61,6.07
TR_000458460,2100-12-08 18:00:00,ST0326,-1.76,-0.93,1.79,3.05,-2.82,-2.80,4.18
TR_000619915,2100-12-08 19:00:00,ST0326,-2.44,-1.76,0.41,3.42,-3.21,-3.30,5.32
TR_000054120,2100-12-08 20:00:00,ST0326,-2.42,-2.44,-0.93,2.79,-2.65,-2.69,5.30
TR_000308818,2100-12-09 06:00:00,ST0326,-2.08,-0.55,1.54,2.42,-1.76,-2.82,4.04
TR_000694613,2100-12-09 07:00:00,ST0326,-2.47,-2.08,0.61,2.88,-2.44,-3.21,5.18
TR_000679349,2100-12-09 08:00:00,ST0326,-2.47,-2.47,-0.55,2.43,-2.42,-2.65,5.41
TR_000602839,2100-12-27 03:00:00,ST0326,-1.59,-0.59,2.14,3.39,-3.04,-2.19,4.01
TR_000020293,2100-12-27 04:00:00,ST0326,-2.48,-1.59,0.79,3.60,-3.46,-2.51,5.14
TR_000710390,2100-12-27 05:00:00,ST0326,-2.75,-2.48,-0.59,3.11,-2.82,-1.90,5.41
TR_000371317,2100-12-27 06:00:00,ST0326,-2.05,-2.75,-1.59,2.14,-1.33,-0.61,4.71
TR_000209827,2101-01-26 00:00:00,ST0326,-2.09,-0.57,0.36,2.52,-1.38,-0.82,4.23
TR_000329351,2101-02-05 07:00:00,ST0326,-2.62,-1.72,1.06,2.63,-1.95,-3.43,5.65
TR_000391840,2101-02-15 00:00:00,ST0326,-3.25,-3.90,-2.53,1.55,-2.73,-2.06,6.73
TR_000214033,2101-02-25 01:00:00,ST0326,-1.36,-0.44,2.00,2.93,-2.78,-1.86,3.48
TR_000744980,2101-02-25 02:00:00,ST0326,-2.19,-1.36,0.86,3.15,-3.13,-2.02,4.58
TR_000319071,2101-02-25 03:00:00,ST0326,-2.51,-2.19,-0.44,2.85,-2.59,-1.60,4.90
TR_000362477,2101-03-07 02:00:00,ST0326,-1.72,-0.77,1.53,3.71,-2.95,-3.27,5.50
TR_000571092,2101-03-07 03:00:00,ST0326,-3.42,-1.72,0.35,3.72,-3.73,-3.85,7.59
TR_000681831,2101-03-07 04:00:00,ST0326,-3.81,-3.42,-0.77,2.88,-3.45,-3.15,7.98
TR_000480712,2101-03-07 14:00:00,ST0326,-1.91,-0.77,2.33,3.78,-1.72,-2.95,5.30
TR_000017610,2101-03-07 15:00:00,ST0326,-2.91,-1.91,0.85,4.17,-3.42,-3.73,6.67
TR_000598041,2101-03-07 16:00:00,ST0326,-3.37,-2.91,-0.77,3.57,-3.81,-3.45,7.13
TR_000126052,2101-03-07 17:00:00,ST0326,-2.52,-3.37,-1.91,2.33,-2.37,-1.80,6.28
TR_000446040,2101-03-08 02:00:00,ST0326,-1.29,-0.19,2.33,3.39,-1.91,-1.72,3.87
TR_000253962,2101-03-08 03:00:00,ST0326,-2.37,-1.29,0.83,3.76,-2.91,-3.42,5.97
TR_000088487,2101-03-08 04:00:00,ST0326,-3.51,-2.37,-0.19,3.52,-3.37,-3.81,7.18
TR_000477612,2101-03-08 05:00:00,ST0326,-3.29,-3.51,-1.29,2.33,-2.52,-2.37,6.96
TR_000318666,2101-03-08 15:00:00,ST0326,-1.21,-0.63,1.61,3.60,-2.37,-2.91,3.90
TR_000726929,2101-03-08 16:00:00,ST0326,-2.77,-1.21,0.40,3.67,-3.51,-3.37,5.81
TR_000568794,2101-03-08 17:00:00,ST0326,-3.41,-2.77,-0.63,2.93,-3.29,-2.52,6.45
TR_000065160,2101-04-16 04:00:00,ST0326,-1.78,-1.10,1.12,2.43,-2.02,-2.26,4.09
TR_000721179,2101-04-16 05:00:00,ST0326,-2.19,-1.78,-0.13,2.55,-2.45,-2.45,4.79
TR_000560131,2101-04-16 16:00:00,ST0326,-1.83,-0.85,1.43,2.31,-1.78,-2.02,3.74
TR_000436734,2101-05-16 03:00:00,ST0326,-1.60,-0.98,0.81,2.66,-2.60,-2.27,3.15
TR_000030660,2101-05-16 04:00:00,ST0326,-1.84,-1.60,-0.25,2.39,-2.17,-2.09,3.55
TR_000022163,2101-06-05 03:00:00,ST0326,-2.57,-1.17,0.91,2.03,-1.65,-2.81,5.26
TR_000072142,2101-06-05 04:00:00,ST0326,-2.94,-2.57,0.00,2.25,-2.23,-2.87,6.17
TR_000259962,2101-06-05 05:00:00,ST0326,-2.64,-2.94,-1.17,1.72,-2.13,-2.14,5.87
TR_000057292,2101-06-05 16:00:00,ST0326,-1.97,-1.28,1.10,3.23,-2.94,-2.23,4.27
TR_000030035,2101-06-05 17:00:00,ST0326,-2.46,-1.97,-0.22,3.13,-2.64,-2.13,4.76
TR_000379352,2101-06-05 18:00:00,ST0326,-2.03,-2.46,-1.28,2.26,-1.75,-1.26,4.33
TR_000352435,2101-07-05 04:00:00,ST0326,-2.39,-1.47,1.54,2.64,-2.39,-2.83,5.49
TR_000258491,2101-07-05 05:00:00,ST0326,-3.10,-2.39,0.23,3.15,-3.14,-3.48,6.43
TR_000170604,2101-07-05 06:00:00,ST0326,-3.27,-3.10,-1.47,2.66,-2.84,-3.06,6.61
TR_000250476,2101-07-05 07:00:00,ST0326,-2.52,-3.27,-2.39,1.54,-2.07,-1.47,5.86
TR_000121447,2101-09-13 06:00:00,ST0326,-2.78,-1.92,0.72,2.55,-2.29,-2.84,5.83
TR_000273455,2101-09-13 07:00:00,ST0326,-3.41,-2.78,-0.83,2.69,-2.87,-3.01,6.72
TR_000048281,2101-09-13 08:00:00,ST0326,-2.94,-3.41,-1.92,1.80,-2.39,-2.14,6.25
TR_000182678,2101-09-23 08:00:00,ST0326,-2.54,-1.85,0.46,1.89,-1.77,-2.65,5.10
TR_000287766,2101-09-23 09:00:00,ST0326,-2.23,-2.54,-0.16,2.01,-1.96,-2.31,5.16
TR_000402897,2101-09-23 21:00:00,ST0326,-1.87,-1.20,0.65,2.93,-2.23,-1.96,3.89
TR_000595034,2101-09-23 22:00:00,ST0326,-1.94,-1.87,-0.30,2.56,-2.20,-1.27,3.96
TR_000067887,2101-10-23 10:00:00,ST0326,-2.10,-1.43,0.86,2.45,-2.66,-2.47,4.44
TR_000695627,2101-10-23 11:00:00,ST0326,-2.68,-2.10,-0.46,2.67,-2.76,-2.43,5.32
TR_000017381,2101-10-23 12:00:00,ST0326,-2.31,-2.68,-1.43,1.72,-2.06,-1.63,4.95
TR_000127673,2101-11-02 00:00:00,ST0326,-1.86,-0.97,1.69,2.35,-1.84,-2.30,4.03
TR_000452886,2101-11-02 01:00:00,ST0326,-2.75,-1.86,0.54,2.72,-2.64,-2.93,5.86
TR_000134854,2101-11-02 02:00:00,ST0326,-3.15,-2.75,-0.97,2.61,-2.92,-2.63,6.39
TR_000710163,2101-11-02 03:00:00,ST0326,-2.73,-3.15,-1.86,1.69,-2.09,-1.58,5.97
TR_000470909,2101-11-02 13:00:00,ST0326,-2.01,-1.25,1.54,3.11,-2.75,-2.64,4.67
TR_000293486,2101-11-02 14:00:00,ST0326,-2.76,-2.01,0.05,3.24,-3.15,-2.92,5.62
TR_000180744,2101-11-02 15:00:00,ST0326,-2.84,-2.76,-1.25,2.56,-2.73,-2.09,5.70
TR_000424994,2101-12-22 00:00:00,ST0326,-2.99,-2.37,-0.71,2.04,-2.26,-3.21,5.92
TR_000228341,2101-12-22 01:00:00,ST0326,-2.67,-2.99,-1.69,1.58,-2.30,-2.51,5.60
TR_000723209,2102-03-02 02:00:00,ST0326,-2.05,-1.15,1.27,3.03,-2.54,-2.62,4.43
TR_000464350,2102-03-02 03:00:00,ST0326,-2.80,-2.05,-0.10,3.04,-2.89,-2.84,5.60
TR_000539026,2102-03-02 04:00:00,ST0326,-2.50,-2.80,-1.15,2.39,-2.24,-2.12,5.30
TR_000000182,2102-03-02 14:00:00,ST0326,-1.78,-0.92,1.41,2.38,-2.05,-2.54,3.98
TR_000732440,2102-03-02 15:00:00,ST0326,-2.41,-1.78,0.24,2.80,-2.80,-2.89,5.16
TR_000201478,2102-03-02 16:00:00,ST0326,-2.57,-2.41,-0.92,2.40,-2.50,-2.24,5.32
TR_000124044,2102-03-03 03:00:00,ST0326,-1.30,-1.15,1.11,2.75,-2.41,-2.80,3.70
TR_000236167,2102-04-01 00:00:00,ST0326,-3.00,-1.63,-0.18,3.25,-3.45,-3.01,6.30
TR_000536674,2102-04-01 01:00:00,ST0326,-2.43,-3.00,-1.16,2.03,-1.71,-0.99,5.73
TR_000194494,2102-04-01 11:00:00,ST0326,-2.61,-0.87,0.51,3.30,-1.63,-3.31,6.03
TR_000445745,2102-05-11 00:00:00,ST0326,-2.57,-1.95,0.58,2.67,-2.27,-2.98,5.84
TR_000034884,2102-05-11 01:00:00,ST0326,-3.19,-2.57,-0.83,2.65,-2.75,-2.91,6.79
TR_000476567,2102-05-11 02:00:00,ST0326,-2.56,-3.19,-1.95,1.78,-2.20,-1.95,6.16
TR_000325293,2102-06-10 10:00:00,ST0326,-1.63,-0.88,1.47,3.22,-2.55,-1.80,4.06
TR_000280137,2102-06-10 11:00:00,ST0326,-2.09,-1.63,0.24,3.16,-2.57,-1.84,4.54
TR_000078919,2102-06-10 12:00:00,ST0326,-1.83,-2.09,-0.88,2.57,-1.67,-1.16,4.28
TR_000437629,2102-06-20 00:00:00,ST0326,-2.66,-2.08,0.01,2.20,-2.09,-3.26,5.13
TR_000070198,2102-06-20 01:00:00,ST0326,-2.76,-2.66,-0.92,2.28,-2.64,-3.13,5.27
TR_000465242,2102-06-20 02:00:00,ST0326,-2.73,-2.76,-2.08,1.38,-2.00,-2.20,5.24
TR_000162382,2102-07-20 10:00:00,ST0326,-2.23,-1.45,0.81,3.03,-2.73,-3.30,5.09
TR_000503802,2102-07-20 11:00:00,ST0326,-2.65,-2.23,-0.59,2.85,-2.69,-2.97,5.62
TR_000002553,2102-07-20 12:00:00,ST0326,-2.15,-2.65,-1.45,1.96,-0.61,-1.71,5.12
TR_000189682,2102-08-19 05:00:00,ST0326,-2.34,-1.50,0.77,2.26,-2.15,-2.84,3.91
TR_000674380,2102-08-19 06:00:00,ST0326,-2.92,-2.34,-0.48,2.27,-2.74,-3.27,5.04
TR_000231487,2102-08-19 07:00:00,ST0326,-2.97,-2.92,-1.50,1.97,-2.45,-2.85,5.09
TR_000161761,2102-09-18 09:00:00,ST0326,-1.58,-1.10,1.09,2.53,-2.18,-3.00,4.14
TR_000003945,2102-09-18 10:00:00,ST0326,-3.20,-1.58,-0.03,2.66,-2.65,-3.37,6.27
TR_000025359,2102-09-18 11:00:00,ST0326,-3.12,-3.20,-1.10,2.11,-2.43,-2.82,6.19
TR_000627120,2102-10-08 00:00:00,ST0326,-2.81,-2.56,0.45,3.05,-2.75,-3.14,6.43
TR_000633371,2102-10-08 01:00:00,ST0326,-3.12,-2.81,-1.22,2.36,-2.66,-2.35,6.74
TR_000027288,2102-11-17 02:00:00,ST0326,-2.43,-1.22,0.41,2.29,-1.90,-2.47,4.81
TR_000354792,2103-01-26 08:00:00,ST0326,-2.26,-1.68,0.11,1.89,-1.86,-2.80,4.38
TR_000014469,2103-01-26 09:00:00,ST0326,-2.70,-2.26,-0.82,1.75,-2.29,-3.06,5.27
TR_000039182,2103-02-25 05:00:00,ST0326,-1.73,-1.12,1.04,2.96,-2.82,-2.46,3.69
TR_000381112,2103-02-25 06:00:00,ST0326,-2.36,-1.73,-0.19,2.98,-2.77,-2.23,4.88
TR_000150994,2103-02-25 07:00:00,ST0326,-1.89,-2.36,-1.12,2.20,-1.83,-1.69,4.41
TR_000442844,2103-02-25 18:00:00,ST0326,-2.72,-2.03,-0.63,2.52,-2.36,-2.77,5.59
TR_000338988,2103-02-26 07:00:00,ST0326,-1.77,-0.95,-0.06,2.57,-2.22,-1.89,4.03
TR_000215420,2103-02-26 18:00:00,ST0326,-2.31,-0.78,0.47,2.26,-0.95,-2.72,4.80
TR_000699721,2103-02-26 19:00:00,ST0326,-2.27,-2.31,-0.27,2.08,-1.77,-2.22,4.93
TR_000063744,2103-03-27 05:00:00,ST0326,-2.37,-1.41,0.60,2.35,-1.53,-2.44,4.82
TR_000067708,2103-03-27 06:00:00,ST0326,-2.71,-2.37,-0.76,2.34,-2.51,-2.29,5.18
TR_000438906,2103-04-16 00:00:00,ST0326,-2.35,-1.48,0.93,3.42,-3.63,-2.93,4.54
TR_000520687,2103-04-16 01:00:00,ST0326,-2.83,-2.35,-0.51,3.13,-3.30,-2.60,5.41
TR_000311694,2103-04-16 02:00:00,ST0326,-2.19,-2.83,-1.48,2.26,-1.94,-1.33,4.77
TR_000304435,2103-04-16 12:00:00,ST0326,-3.26,-1.08,0.40,2.19,-2.35,-3.63,6.63
TR_000067265,2103-04-16 13:00:00,ST0326,-3.73,-3.26,-0.55,2.58,-2.83,-3.30,7.25
TR_000165402,2103-04-16 14:00:00,ST0326,-2.81,-3.73,-1.08,1.35,-2.19,-1.94,6.33
TR_000290519,2103-05-06 07:00:00,ST0326,-1.44,-0.20,2.00,3.10,-1.40,-1.56,3.71
TR_000397771,2103-05-06 08:00:00,ST0326,-1.91,-1.44,0.75,3.26,-2.94,-1.85,4.41
TR_000542839,2103-05-06 09:00:00,ST0326,-2.36,-1.91,-0.20,2.87,-2.48,-1.37,4.86
TR_000715277,2103-05-06 20:00:00,ST0326,-1.80,-1.15,0.53,2.50,-1.91,-2.94,5.21
TR_000471181,2103-05-06 21:00:00,ST0326,-3.24,-1.80,-0.15,2.20,-2.36,-2.48,6.72
TR_000450104,2103-05-07 08:00:00,ST0326,-0.72,-0.12,1.86,3.41,-1.80,-1.91,3.38
TR_000341750,2103-05-07 09:00:00,ST0326,-1.37,-0.72,0.86,3.48,-3.24,-2.36,4.28
TR_000398693,2103-05-07 10:00:00,ST0326,-2.39,-1.37,-0.12,2.99,-2.32,-1.72,5.30
TR_000306346,2103-06-05 06:00:00,ST0326,-1.92,-1.18,1.28,2.09,-1.21,-2.19,4.39
TR_000373486,2103-06-05 07:00:00,ST0326,-2.60,-1.92,0.04,2.34,-1.85,-2.58,5.77
TR_000060230,2103-06-05 08:00:00,ST0326,-2.66,-2.60,-1.18,2.13,-1.90,-2.12,5.83
TR_000456294,2103-06-05 19:00:00,ST0326,-1.93,-1.10,1.30,3.17,-2.60,-1.85,4.24
TR_000204826,2103-06-05 20:00:00,ST0326,-2.25,-1.93,0.00,3.03,-2.66,-1.90,4.72
TR_000607556,2103-06-05 21:00:00,ST0326,-2.14,-2.25,-1.10,2.45,-1.74,-1.22,4.61
TR_000346938,2103-06-06 07:00:00,ST0326,-2.33,-1.67,0.66,2.31,-1.93,-2.60,5.43
TR_000223731,2103-06-06 08:00:00,ST0326,-2.94,-2.33,-0.58,2.47,-2.25,-2.66,6.28
TR_000118686,2103-06-06 09:00:00,ST0326,-2.65,-2.94,-1.67,1.62,-2.14,-1.74,5.99
TR_000205200,2103-06-06 21:00:00,ST0326,-2.44,-0.66,0.53,2.90,-2.65,-2.14,5.44
TR_000405074,2103-06-06 22:00:00,ST0326,-2.12,-2.44,-0.13,2.01,-1.13,-0.93,5.12
TR_000023165,2103-06-07 10:00:00,ST0326,-2.84,-1.15,-0.25,1.63,-2.12,-1.13,6.28
TR_000185691,2103-06-07 21:00:00,ST0326,-1.01,-0.54,0.73,3.44,-1.15,-2.44,4.19
TR_000000909,2103-06-08 09:00:00,ST0326,-0.99,-0.51,0.63,3.18,-1.01,-1.15,4.55
TR_000327072,2103-06-08 21:00:00,ST0326,-2.12,-0.30,1.01,3.56,-0.99,-1.01,5.20
TR_000662935,2103-06-08 22:00:00,ST0326,-3.14,-2.12,0.33,3.05,-1.32,-1.34,6.22
TR_000675808,2103-06-09 09:00:00,ST0326,-2.82,-0.92,0.76,3.08,-2.12,-0.99,6.08
TR_000677340,2103-06-09 10:00:00,ST0326,-2.97,-2.82,0.06,2.81,-3.14,-1.32,6.23
TR_000707788,2103-06-09 11:00:00,ST0326,-2.19,-2.97,-0.92,1.82,-1.73,-1.95,5.45
TR_000099303,2103-06-09 21:00:00,ST0326,-1.38,-0.44,1.11,3.26,-2.82,-2.12,4.24
TR_000259458,2103-06-09 22:00:00,ST0326,-2.90,-1.38,0.21,3.20,-2.97,-3.14,5.99
TR_000301698,2103-06-09 23:00:00,ST0326,-2.74,-2.90,-0.44,2.40,-2.19,-1.73,5.83
TR_000666379,2103-06-10 10:00:00,ST0326,-2.80,-0.81,0.29,3.09,-2.90,-2.97,5.85
TR_000376053,2103-06-10 11:00:00,ST0326,-2.63,-2.80,-0.33,2.34,-2.74,-2.19,5.68
TR_000391479,2103-06-11 00:00:00,ST0326,-2.69,-1.02,-0.16,1.62,-1.43,-1.25,5.68

Val | ST0358 | 71개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000749200,2103-06-15 00:00:00,ST0358,-2.64,-2.65,-1.73,3.32,-2.72,-2.64,6.84
TR_000263461,2103-06-15 01:00:00,ST0358,-2.10,-2.64,-2.65,1.97,-1.70,-1.00,6.30
TR_000596538,2103-06-25 03:00:00,ST0358,-2.19,-0.40,3.01,2.61,-1.45,-2.86,4.82
TR_000457634,2103-06-25 04:00:00,ST0358,-2.85,-2.19,1.53,3.87,-2.94,-2.86,7.38
TR_000293983,2103-07-05 01:00:00,ST0358,-1.95,-0.85,1.67,2.61,-1.98,-2.49,4.24
TR_000121400,2103-07-05 02:00:00,ST0358,-2.69,-1.95,0.33,2.82,-2.28,-2.36,5.80
TR_000082870,2103-07-05 03:00:00,ST0358,-2.65,-2.69,-0.85,2.42,-1.79,-1.56,5.87
TR_000339809,2103-07-15 05:00:00,ST0358,-0.56,0.99,4.58,3.85,-1.77,-1.36,2.53
TR_000568701,2103-07-15 06:00:00,ST0358,-1.99,-0.56,3.11,4.81,-2.04,-2.02,5.85
TR_000476138,2103-07-15 07:00:00,ST0358,-2.54,-1.99,0.99,5.08,-2.48,-2.52,6.79
TR_000506878,2103-07-15 08:00:00,ST0358,-2.56,-2.54,-0.56,4.58,-2.47,-2.36,6.81
TR_000497772,2103-07-15 09:00:00,ST0358,-2.18,-2.56,-1.99,3.11,-1.30,-0.44,6.43
TR_000251550,2103-07-15 18:00:00,ST0358,-2.46,-1.30,2.56,3.86,-1.99,-2.04,6.69
TR_000725101,2103-07-15 19:00:00,ST0358,-2.46,-2.46,0.70,4.25,-2.54,-2.48,7.70
TR_000186657,2103-07-15 20:00:00,ST0358,-2.46,-2.46,-1.30,3.84,-2.56,-2.47,7.70
TR_000735931,2103-07-15 21:00:00,ST0358,-2.46,-2.46,-2.46,2.56,-2.18,-1.30,7.70
TR_000126116,2103-08-04 08:00:00,ST0358,-1.50,-0.32,2.74,4.00,-2.35,-1.69,4.69
TR_000451453,2103-08-04 09:00:00,ST0358,-2.38,-1.50,1.24,4.24,-2.35,-1.85,5.85
TR_000105327,2103-08-04 10:00:00,ST0358,-2.39,-2.38,-0.32,3.81,-2.35,-2.39,5.86
TR_000370176,2103-08-14 08:00:00,ST0358,-1.10,-0.59,1.45,3.38,-1.92,-0.78,3.69
TR_000291722,2103-08-14 09:00:00,ST0358,-1.09,-1.10,0.35,3.06,-0.95,-0.28,3.68
TR_000558275,2103-08-14 20:00:00,ST0358,-2.28,-1.50,0.60,2.59,-1.10,-1.92,5.41
TR_000248706,2103-08-14 21:00:00,ST0358,-1.99,-2.28,-0.42,2.24,-1.09,-0.95,5.29
TR_000621911,2103-08-24 01:00:00,ST0358,-2.27,-1.24,1.35,2.74,-1.73,-2.55,5.33
TR_000338871,2103-08-24 02:00:00,ST0358,-2.54,-2.27,0.06,2.94,-2.50,-2.55,5.99
TR_000328148,2103-08-24 03:00:00,ST0358,-2.45,-2.54,-1.24,2.36,-2.17,-2.19,5.90
TR_000162459,2103-09-03 03:00:00,ST0358,-1.46,-0.29,2.14,2.81,-1.76,-2.02,3.46
TR_000100239,2103-09-03 04:00:00,ST0358,-2.26,-1.46,1.06,3.08,-2.14,-1.79,5.12
TR_000515644,2103-09-23 07:00:00,ST0358,-1.61,-0.72,1.88,3.49,-2.42,-2.29,4.77
TR_000744649,2103-09-23 08:00:00,ST0358,-1.72,-1.61,0.51,3.72,-2.39,-1.79,5.01
TR_000504179,2103-09-23 09:00:00,ST0358,-1.46,-1.72,-0.72,3.02,-1.57,-0.84,4.75
TR_000229017,2103-09-23 19:00:00,ST0358,-1.55,-0.95,1.68,3.16,-1.61,-2.42,5.04
TR_000746784,2103-09-23 20:00:00,ST0358,-1.77,-1.55,0.56,3.29,-1.72,-2.39,5.70
TR_000121385,2103-09-23 21:00:00,ST0358,-1.85,-1.77,-0.95,2.65,-1.46,-1.57,5.78
TR_000127497,2103-09-24 07:00:00,ST0358,-1.22,0.16,2.96,3.49,-1.55,-1.61,3.53
TR_000159311,2103-10-03 01:00:00,ST0358,-2.02,-0.95,1.64,2.30,-1.32,-2.46,4.66
TR_000444794,2103-10-03 02:00:00,ST0358,-2.47,-2.02,0.53,2.76,-2.20,-2.46,5.73
TR_000317886,2103-10-03 03:00:00,ST0358,-2.47,-2.47,-0.95,2.39,-2.16,-2.35,5.73
TR_000003133,2103-10-13 00:00:00,ST0358,-1.12,0.00,2.35,4.02,-2.31,-1.54,4.25
TR_000105535,2103-10-13 01:00:00,ST0358,-2.47,-1.12,0.85,4.08,-2.32,-2.11,5.91
TR_000534330,2103-10-13 02:00:00,ST0358,-2.27,-2.47,0.00,3.50,-1.97,-1.52,5.71
TR_000527462,2103-10-23 06:00:00,ST0358,-1.97,-0.95,1.57,3.38,-2.15,-2.27,4.56
TR_000096029,2103-10-23 07:00:00,ST0358,-2.17,-1.97,0.32,3.25,-2.15,-2.30,5.16
TR_000070392,2103-10-23 08:00:00,ST0358,-1.75,-2.17,-0.95,2.65,-1.18,-1.07,4.74
TR_000378657,2103-11-12 05:00:00,ST0358,-2.57,-1.34,1.74,2.75,-1.77,-2.81,6.01
TR_000143886,2103-11-12 06:00:00,ST0358,-2.55,-2.57,0.29,3.17,-2.78,-2.83,6.79
TR_000225854,2103-11-12 08:00:00,ST0358,-2.36,-1.02,-2.57,1.74,-1.61,-0.89,6.60
TR_000708701,2103-11-12 17:00:00,ST0358,-0.97,0.53,3.45,3.44,-2.57,-1.77,3.39
TR_000044578,2103-11-12 18:00:00,ST0358,-2.23,-0.97,2.11,4.24,-2.55,-2.78,5.70
TR_000173136,2103-11-12 19:00:00,ST0358,-2.74,-2.23,0.53,4.22,-1.02,-2.80,6.21
TR_000734307,2103-11-12 20:00:00,ST0358,-2.29,-2.74,-0.97,3.45,-2.36,-1.61,5.76
TR_000550773,2103-11-13 06:00:00,ST0358,-0.61,-0.44,1.48,3.47,-2.23,-2.55,4.59
TR_000353217,2103-11-13 07:00:00,ST0358,-2.81,-0.61,-0.32,3.36,-2.74,-1.02,7.08
TR_000000442,2103-11-13 08:00:00,ST0358,-2.82,-2.81,-0.44,2.56,-2.29,-2.36,7.09
TR_000589063,2103-12-02 03:00:00,ST0358,-1.89,-0.52,1.87,2.88,-2.19,-0.75,3.88
TR_000610578,2103-12-02 04:00:00,ST0358,-2.58,-1.89,0.70,3.11,-2.62,-0.92,5.31
TR_000223333,2103-12-02 05:00:00,ST0358,-2.51,-2.58,-0.52,2.70,-1.88,-1.08,5.32
TR_000276842,2103-12-22 00:00:00,ST0358,-2.24,-2.21,-2.17,2.16,-1.81,-0.76,6.96
TR_000186626,2103-12-22 09:00:00,ST0358,-1.22,0.49,3.81,3.86,-2.17,-2.16,4.27
TR_000545241,2103-12-22 10:00:00,ST0358,-2.17,-1.22,2.20,4.65,-2.20,-2.17,6.55
TR_000249921,2103-12-22 11:00:00,ST0358,-2.17,-2.17,0.49,4.72,-2.21,-2.16,6.69
TR_000730066,2103-12-22 12:00:00,ST0358,-2.17,-2.17,-1.22,3.81,-2.24,-1.81,6.69
TR_000340431,2104-01-01 00:00:00,ST0358,-2.31,-1.07,1.83,2.48,-1.55,-2.69,5.48
TR_000380901,2104-01-11 03:00:00,ST0358,-2.04,-1.00,2.06,3.65,-2.08,-2.06,5.49
TR_000433203,2104-01-11 04:00:00,ST0358,-2.03,-2.04,0.71,3.67,-2.10,-2.04,5.69
TR_000604514,2104-01-11 05:00:00,ST0358,-2.05,-2.03,-1.00,3.02,-2.09,-1.31,5.71
TR_000642071,2104-01-21 00:00:00,ST0358,-2.13,-1.65,1.67,3.43,-2.20,-2.14,5.81
TR_000746720,2104-02-10 23:00:00,ST0358,-1.32,-0.82,0.81,2.75,-1.67,-0.62,3.71
TR_000284394,2104-02-20 04:00:00,ST0358,-1.74,-0.46,2.54,4.13,-2.43,-2.55,4.55
TR_000661218,2104-02-20 05:00:00,ST0358,-2.41,-1.74,1.10,4.28,-2.48,-2.61,5.67
TR_000289204,2104-02-20 06:00:00,ST0358,-2.41,-2.41,-0.46,3.72,-2.45,-2.03,5.67

Val | ST0292 | 42개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000334066,2103-06-15 00:00:00,ST0292,-2.86,-2.21,-0.44,2.34,-2.86,-3.14,5.09
TR_000555520,2103-06-15 01:00:00,ST0292,-3.43,-2.86,-1.41,1.80,-3.40,-3.62,5.66
TR_000395312,2103-06-15 02:00:00,ST0292,-3.33,-3.43,-2.21,0.69,-2.95,-2.72,5.56
TR_000135563,2103-07-05 03:00:00,ST0292,-2.80,-2.15,-0.56,1.35,-2.97,-3.40,3.93
TR_000464849,2103-07-15 08:00:00,ST0292,-2.12,-1.50,0.42,3.45,-2.95,-2.69,4.60
TR_000040410,2103-07-15 09:00:00,ST0292,-2.65,-2.12,-0.70,3.06,-3.47,-3.14,5.13
TR_000095272,2103-07-15 10:00:00,ST0292,-2.95,-2.65,-1.50,1.64,-2.75,-2.27,5.43
TR_000006962,2103-07-15 20:00:00,ST0292,-2.32,-1.71,0.13,2.48,-2.12,-2.95,5.52
TR_000665206,2103-07-15 21:00:00,ST0292,-2.85,-2.32,-0.91,2.35,-2.65,-3.47,6.39
TR_000046636,2103-07-15 22:00:00,ST0292,-3.20,-2.85,-1.71,1.32,-2.95,-2.75,6.74
TR_000554746,2103-08-04 10:00:00,ST0292,-2.34,-1.68,0.19,2.58,-3.27,-2.79,3.96
TR_000024742,2103-08-04 11:00:00,ST0292,-2.89,-2.34,-0.85,2.19,-3.67,-3.12,4.51
TR_000716860,2103-08-14 10:00:00,ST0292,-2.58,-2.23,-0.91,1.43,-2.88,-2.18,3.44
TR_000619588,2103-08-14 22:00:00,ST0292,-3.40,-2.89,-1.61,0.64,-2.58,-2.88,4.97
TR_000158078,2103-08-24 03:00:00,ST0292,-3.03,-2.43,-0.90,1.20,-2.62,-3.31,4.62
TR_000746479,2103-08-24 04:00:00,ST0292,-3.50,-3.03,-1.74,0.85,-3.11,-3.53,5.17
TR_000624934,2103-09-13 10:00:00,ST0292,-3.17,-2.57,-1.09,1.09,-2.97,-3.61,4.90
TR_000458648,2103-09-13 11:00:00,ST0292,-3.62,-3.17,-1.88,0.64,-3.33,-3.18,5.35
TR_000675395,2103-09-23 09:00:00,ST0292,-2.70,-2.09,-0.46,2.06,-3.43,-3.13,4.51
TR_000549213,2103-09-23 10:00:00,ST0292,-3.05,-2.70,-1.37,1.43,-3.19,-2.62,4.86
TR_000337565,2103-09-23 21:00:00,ST0292,-2.79,-2.19,-0.56,1.81,-2.70,-3.43,4.98
TR_000498202,2103-09-23 22:00:00,ST0292,-3.27,-2.79,-1.44,1.30,-3.05,-3.19,5.46
TR_000131391,2103-10-13 02:00:00,ST0292,-2.33,-1.72,-0.01,2.66,-2.80,-2.53,4.26
TR_000489746,2103-10-13 03:00:00,ST0292,-2.78,-2.33,-0.96,2.04,-3.04,-2.78,4.71
TR_000226390,2103-10-23 08:00:00,ST0292,-2.80,-2.18,-0.67,1.72,-3.19,-3.15,3.89
TR_000289253,2103-10-23 09:00:00,ST0292,-3.25,-2.80,-1.48,1.10,-2.96,-2.76,4.47
TR_000079783,2103-11-12 07:00:00,ST0292,-2.79,-2.14,-0.39,1.72,-2.34,-3.09,5.34
TR_000372367,2103-11-12 08:00:00,ST0292,-3.31,-2.79,-1.35,1.53,-2.90,-3.42,6.21
TR_000136051,2103-11-12 19:00:00,ST0292,-1.78,-0.99,1.08,2.55,-2.79,-2.34,3.49
TR_000033466,2103-11-12 20:00:00,ST0292,-2.39,-1.78,-0.03,2.90,-3.31,-2.90,4.53
TR_000026353,2103-11-12 21:00:00,ST0292,-2.84,-2.39,-0.99,2.18,-3.18,-2.75,4.98
TR_000592466,2103-11-13 08:00:00,ST0292,-2.53,-2.04,-0.57,2.14,-2.39,-3.31,5.62
TR_000066984,2103-12-02 05:00:00,ST0292,-2.55,-1.92,-0.28,1.87,-2.68,-2.82,3.71
TR_000739255,2103-12-02 06:00:00,ST0292,-3.06,-2.55,-1.18,1.43,-2.96,-3.14,4.64
TR_000469223,2103-12-22 00:00:00,ST0292,-3.25,-2.65,-1.13,1.81,-3.19,-3.70,6.23
TR_000188663,2103-12-22 01:00:00,ST0292,-3.68,-3.25,-1.96,0.90,-3.28,-2.83,6.66
TR_000456558,2103-12-22 11:00:00,ST0292,-1.88,-1.04,1.12,2.40,-2.65,-2.62,3.59
TR_000714924,2103-12-22 12:00:00,ST0292,-2.56,-1.88,0.01,2.98,-3.25,-3.19,5.34
TR_000696194,2104-01-11 05:00:00,ST0292,-2.58,-1.92,-0.10,2.07,-3.08,-3.21,4.46
TR_000338905,2104-02-20 06:00:00,ST0292,-2.40,-1.73,0.13,2.68,-3.22,-2.82,3.80
TR_000185189,2104-02-20 07:00:00,ST0292,-2.95,-2.40,-0.87,2.19,-3.64,-3.16,4.43
TR_000546127,2104-02-20 08:00:00,ST0292,-2.90,-2.95,-1.73,1.18,-2.75,-2.25,4.38

Val | ST0326 | 46개

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,target_maxrise_6h
row_id,,,,,,,,,
TR_000466466,2103-06-25 02:00:00,ST0326,-2.46,-1.51,1.41,2.59,-1.74,-3.27,5.37
TR_000094091,2103-06-25 03:00:00,ST0326,-3.43,-2.46,-0.09,2.90,-2.69,-3.79,7.20
TR_000666483,2103-06-25 04:00:00,ST0326,-3.84,-3.43,-1.51,2.53,-3.02,-3.31,7.71
TR_000451727,2103-07-05 01:00:00,ST0326,-2.40,-1.81,-0.42,2.05,-1.87,-1.83,4.83
TR_000578936,2103-07-15 04:00:00,ST0326,-1.45,-0.39,2.87,3.25,-2.64,-2.03,3.59
TR_000187929,2103-07-15 05:00:00,ST0326,-2.53,-1.45,1.46,3.67,-3.40,-2.95,5.37
TR_000150178,2103-07-15 06:00:00,ST0326,-3.23,-2.53,-0.39,3.63,-3.63,-3.01,6.07
TR_000394852,2103-07-15 07:00:00,ST0326,-2.75,-3.23,-1.45,2.87,-2.60,-1.67,5.59
TR_000284775,2103-07-15 16:00:00,ST0326,-2.11,-0.33,1.92,2.14,-1.45,-2.64,4.46
TR_000255006,2103-07-15 17:00:00,ST0326,-2.78,-2.11,0.95,2.84,-2.53,-3.40,6.41
TR_000252646,2103-07-15 18:00:00,ST0326,-3.57,-2.78,-0.33,2.76,-3.23,-3.63,7.49
TR_000107357,2103-07-15 19:00:00,ST0326,-3.26,-3.57,-2.11,1.92,-2.75,-2.60,7.18
TR_000500868,2103-08-04 07:00:00,ST0326,-1.18,-0.34,1.52,3.12,-3.02,-1.34,3.41
TR_000251596,2103-08-04 08:00:00,ST0326,-1.44,-1.18,0.46,3.09,-2.93,-1.42,3.67
TR_000584538,2103-08-04 09:00:00,ST0326,-2.14,-1.44,-0.34,2.50,-1.93,-1.78,4.37
TR_000456042,2103-08-24 00:00:00,ST0326,-2.34,-1.61,0.08,1.75,-1.67,-2.78,4.49
TR_000125082,2103-08-24 01:00:00,ST0326,-2.37,-2.34,-0.88,1.82,-2.04,-2.58,4.85
TR_000100246,2103-09-03 03:00:00,ST0326,-2.20,-1.74,-0.04,2.17,-1.85,-1.78,4.28
TR_000540996,2103-09-13 07:00:00,ST0326,-2.44,-1.76,-0.08,1.74,-1.93,-2.25,4.79
TR_000604601,2103-09-13 08:00:00,ST0326,-2.52,-2.44,-1.20,1.59,-2.06,-2.02,4.91
TR_000683720,2103-09-23 06:00:00,ST0326,-1.77,-1.02,0.75,2.72,-2.52,-1.92,3.89
TR_000005059,2103-09-23 07:00:00,ST0326,-1.77,-1.77,-0.39,2.42,-2.23,-1.52,3.89
TR_000564641,2103-09-23 18:00:00,ST0326,-2.65,-1.13,0.63,2.12,-1.77,-2.52,5.15
TR_000037456,2103-09-23 19:00:00,ST0326,-2.44,-2.65,-0.14,2.03,-1.77,-2.23,5.50
TR_000317562,2103-09-24 07:00:00,ST0326,-1.34,-0.83,0.91,3.06,-2.44,-1.77,3.25
TR_000713571,2103-10-03 01:00:00,ST0326,-2.31,-2.07,-0.57,1.75,-1.79,-2.56,4.69
TR_000208186,2103-10-13 01:00:00,ST0326,-1.63,-0.48,0.48,2.48,-0.78,-0.36,3.94
TR_000683429,2103-10-23 05:00:00,ST0326,-1.86,-1.25,0.58,2.52,-2.20,-2.33,3.77
TR_000477156,2103-10-23 06:00:00,ST0326,-2.05,-1.86,-0.46,2.23,-1.92,-1.95,4.17
TR_000371946,2103-11-12 05:00:00,ST0326,-2.79,-1.63,-0.18,2.29,-2.01,-2.99,6.06
TR_000375250,2103-11-12 06:00:00,ST0326,-2.81,-2.79,-0.70,1.61,-2.11,-1.78,6.08
TR_000068846,2103-11-12 17:00:00,ST0326,-1.18,-0.73,1.02,3.27,-2.79,-2.01,3.71
TR_000704373,2103-11-12 18:00:00,ST0326,-2.27,-1.18,0.09,3.06,-2.81,-2.11,4.80
TR_000368380,2103-11-13 05:00:00,ST0326,-1.83,-0.76,0.47,2.53,-1.18,-2.79,5.00
TR_000054677,2103-11-13 06:00:00,ST0326,-2.84,-1.83,-0.28,2.21,-2.27,-2.81,6.10
TR_000500926,2103-12-22 08:00:00,ST0326,-1.96,-0.48,2.33,3.11,-2.77,-2.40,4.70
TR_000357589,2103-12-22 09:00:00,ST0326,-2.59,-1.96,0.77,2.88,-3.38,-2.96,5.95
TR_000496797,2103-12-22 10:00:00,ST0326,-2.81,-2.59,-0.48,3.36,-3.17,-2.62,6.17
TR_000575827,2103-12-22 11:00:00,ST0326,-2.24,-2.81,-1.96,2.33,-2.10,-1.43,5.60
TR_000166517,2104-01-01 00:00:00,ST0326,-2.68,-2.13,-0.49,2.15,-1.89,-2.22,5.73
TR_000467257,2104-01-11 02:00:00,ST0326,-1.38,-1.34,0.74,2.92,-2.24,-2.22,3.92
TR_000177631,2104-01-11 03:00:00,ST0326,-2.33,-1.38,-0.28,2.47,-2.20,-1.92,4.87
TR_000461959,2104-01-21 00:00:00,ST0326,-3.35,-2.85,-1.11,2.29,-2.82,-3.40,6.53
TR_000613885,2104-02-20 03:00:00,ST0326,-1.78,-0.98,1.28,3.18,-3.06,-2.49,3.85
TR_000348560,2104-02-20 04:00:00,ST0326,-2.23,-1.78,0.01,3.07,-2.96,-2.55,4.53
TR_000092225,2104-02-20 05:00:00,ST0326,-2.15,-2.23,-0.98,2.41,-2.02,-1.53,4.45

In [17]:
# wl_diff_6h = 종속변수인 행들은 혹시 조수간만의 차에 의한건가?

# 1. 조건에 해당하는 행 추출
tidal_pattern = train.loc[
    (train['wl_diff_6h'] < -1) &
    ((train['target_maxrise_6h'] + train['wl_diff_6h']).abs() < 0.5)
]

# 2. 관측소별 조건 만족 건수 및 전체 데이터 대비 비율
tidal_station = pd.DataFrame({
    'total_count': train.groupby('station_id').size(),
    'pattern_count': tidal_pattern.groupby('station_id').size()
})

tidal_station['pattern_count'] = tidal_station['pattern_count'].fillna(0).astype(int)

tidal_station['pattern_ratio'] = (
    tidal_station['pattern_count'] / tidal_station['total_count'] * 100
)

# 3. 조건 만족 건수 기준 내림차순 정렬
tidal_station = tidal_station.sort_values(
    'pattern_count', ascending=False
)

display(tidal_station)

            total_count  pattern_count  pattern_ratio
station_id
ST0110             1379            272      19.724438
ST0326             1379            260      18.854242
ST0159             1379            220      15.953590
ST0358             1379            213      15.445975
ST0347             1379            208      15.083394
ST0415              989            201      20.323559
ST0292             1354            200      14.771049
ST0313             1379            124       8.992023
ST0234             1068            106       9.925094
ST0226             1379             35       2.538071
ST0260             1379             29       2.102973
ST0067             1378             26       1.886792
ST0130             1378             22       1.596517
ST0129             1379             18       1.305294
ST0192             1379             16       1.160261
ST0051             1379             12       0.870196
ST0275             1379              9       0.652647
ST0164             1379              6       0.435098
ST0229             1379              5       0.362582
ST0028             1379              3       0.217549
ST0070              991              3       0.302725
ST0261             1002              3       0.299401
ST0428             1379              3       0.217549
ST0123             1077              2       0.185701
ST0398             1337              2       0.149589
ST0006             1379              2       0.145033
ST0068             1379              1       0.072516
ST0050             1379              1       0.072516
ST0178             1379              1       0.072516
ST0065             1368              1       0.073099
ST0191             1379              1       0.072516
ST0062             1340              1       0.074627
ST0269              989              1       0.101112
ST0278             1379              1       0.072516
ST0041             1379              1       0.072516
ST0297             1379              1       0.072516
ST0038             1206              1       0.082919
ST0321             1379              1       0.072516
ST0180             1379              1       0.072516
ST0333              991              1       0.100908
ST0204              989              1       0.101112
ST0408             1379              1       0.072516
ST0020             1378              0       0.000000
ST0021             1379              0       0.000000
ST0022             1379              0       0.000000
ST0023             1379              0       0.000000
ST0024             1379              0       0.000000
ST0025             1379              0       0.000000
ST0026              989              0       0.000000
ST0027             1379              0       0.000000
ST0029             1378              0       0.000000
ST0030             1379              0       0.000000
ST0031             1356              0       0.000000
ST0032             1379              0       0.000000
ST0033             1002              0       0.000000
ST0034             1379              0       0.000000
ST0035             1378              0       0.000000
ST0036             1379              0       0.000000
ST0037             1379              0       0.000000
ST0039             1379              0       0.000000
ST0040             1379              0       0.000000
ST0042             1379              0       0.000000
ST0043             1341              0       0.000000
ST0044             1178              0       0.000000
ST0045             1379              0       0.000000
ST0046             1379              0       0.000000
ST0047             1379              0       0.000000
ST0048             1367              0       0.000000
ST0049             1353              0       0.000000
ST0052             1379              0       0.000000
ST0053             1379              0       0.000000
ST0054             1379              0       0.000000
ST0055             1003              0       0.000000
ST0056             1379              0       0.000000
ST0057             1379              0       0.000000
ST0058             1379              0       0.000000
ST0059             1379              0       0.000000
ST0060             1379              0       0.000000
ST0061             1379              0       0.000000
ST0063             1379              0       0.000000
ST0064             1379              0       0.000000
ST0066              988              0       0.000000
ST0069             1376              0       0.000000
ST0071             1379              0       0.000000
ST0072             1379              0       0.000000
ST0073             1379              0       0.000000
ST0074             1379              0       0.000000
ST0075             1379              0       0.000000
ST0076             1379              0       0.000000
ST0077             1279              0       0.000000
ST0078             1379              0       0.000000
ST0079             1379              0       0.000000
ST0080             1379              0       0.000000
ST0081             1379              0       0.000000
ST0082             1379              0       0.000000
ST0083              989              0       0.000000
ST0084             1379              0       0.000000
ST0085             1379              0       0.000000
ST0086             1379              0       0.000000
ST0087             1379              0       0.000000
ST0088             1283              0       0.000000
ST0089              989              0       0.000000
ST0090             1032              0       0.000000
ST0091             1379              0       0.000000
ST0092             1379              0       0.000000
ST0093             1379              0       0.000000
ST0094             1206              0       0.000000
ST0095             1379              0       0.000000
ST0096             1372              0       0.000000
ST0097             1379              0       0.000000
ST0098             1379              0       0.000000
ST0099             1379              0       0.000000
ST0100             1375              0       0.000000
ST0101             1372              0       0.000000
ST0102             1379              0       0.000000
ST0103             1379              0       0.000000
ST0104             1000              0       0.000000
ST0105             1003              0       0.000000
ST0106             1379              0       0.000000
ST0107             1379              0       0.000000
ST0108             1379              0       0.000000
ST0109             1369              0       0.000000
ST0111             1379              0       0.000000
ST0112             1379              0       0.000000
ST0113             1379              0       0.000000
ST0114             1379              0       0.000000
ST0115              983              0       0.000000
ST0116             1379              0       0.000000
ST0117             1379              0       0.000000
ST0118             1379              0       0.000000
ST0119             1379              0       0.000000
ST0120             1376              0       0.000000
ST0121              982              0       0.000000
ST0122             1379              0       0.000000
ST0124             1379              0       0.000000
ST0125             1379              0       0.000000
ST0126             1379              0       0.000000
ST0127             1379              0       0.000000
ST0128             1379              0       0.000000
ST0131             1379              0       0.000000
ST0132             1379              0       0.000000
ST0133             1379              0       0.000000
ST0134             1379              0       0.000000
ST0135             1379              0       0.000000
ST0136             1379              0       0.000000
ST0137             1379              0       0.000000
ST0138             1379              0       0.000000
ST0139             1032              0       0.000000
ST0140             1352              0       0.000000
ST0141             1379              0       0.000000
ST0142             1360              0       0.000000
ST0143             1379              0       0.000000
ST0144             1379              0       0.000000
ST0145             1379              0       0.000000
ST0146             1378              0       0.000000
ST0147             1003              0       0.000000
ST0148             1379              0       0.000000
ST0149             1379              0       0.000000
ST0150             1379              0       0.000000
ST0151             1379              0       0.000000
ST0152             1379              0       0.000000
ST0153              984              0       0.000000
ST0154             1379              0       0.000000
ST0155             1379              0       0.000000
ST0156             1379              0       0.000000
ST0157             1379              0       0.000000
ST0158              991              0       0.000000
ST0160             1379              0       0.000000
ST0161             1379              0       0.000000
ST0162             1360              0       0.000000
ST0163             1379              0       0.000000
ST0165             1379              0       0.000000
ST0166             1373              0       0.000000
ST0167             1379              0       0.000000
ST0168             1002              0       0.000000
ST0169             1379              0       0.000000
ST0170             1206              0       0.000000
ST0171             1379              0       0.000000
ST0172             1345              0       0.000000
ST0173             1379              0       0.000000
ST0174             1379              0       0.000000
ST0175             1378              0       0.000000
ST0176             1379              0       0.000000
ST0177             1379              0       0.000000
ST0179             1379              0       0.000000
ST0181             1379              0       0.000000
ST0182             1003              0       0.000000
ST0183             1206              0       0.000000
ST0184             1360              0       0.000000
ST0185             1379              0       0.000000
ST0186             1379              0       0.000000
ST0187             1379              0       0.000000
ST0188              991              0       0.000000
ST0189             1379              0       0.000000
ST0190             1379              0       0.000000
ST0193             1379              0       0.000000
ST0194             1379              0       0.000000
ST0195             1379              0       0.000000
ST0196             1347              0       0.000000
ST0197             1379              0       0.000000
ST0198             1002              0       0.000000
ST0199             1304              0       0.000000
ST0200             1379              0       0.000000
ST0201             1379              0       0.000000
ST0202             1379              0       0.000000
ST0203             1283              0       0.000000
ST0205             1379              0       0.000000
ST0206             1379              0       0.000000
ST0207             1379              0       0.000000
ST0208             1379              0       0.000000
ST0209             1009              0       0.000000
ST0210             1379              0       0.000000
ST0211              989              0       0.000000
ST0212             1379              0       0.000000
ST0213             1379              0       0.000000
ST0214             1369              0       0.000000
ST0215             1379              0       0.000000
ST0216             1379              0       0.000000
ST0217             1379              0       0.000000
ST0218             1378              0       0.000000
ST0219             1379              0       0.000000
ST0220             1379              0       0.000000
ST0221             1379              0       0.000000
ST0222             1379              0       0.000000
ST0223             1379              0       0.000000
ST0224             1379              0       0.000000
ST0225             1379              0       0.000000
ST0227             1360              0       0.000000
ST0228             1379              0       0.000000
ST0230              989              0       0.000000
ST0231             1379              0       0.000000
ST0232             1216              0       0.000000
ST0233             1303              0       0.000000
ST0002             1379              0       0.000000
ST0235             1003              0       0.000000
ST0236             1378              0       0.000000
ST0237             1372              0       0.000000
ST0238             1379              0       0.000000
ST0239             1379              0       0.000000
ST0240             1373              0       0.000000
ST0241             1379              0       0.000000
ST0242             1379              0       0.000000
ST0243             1379              0       0.000000
ST0244             1379              0       0.000000
ST0245             1379              0       0.000000
ST0246             1206              0       0.000000
ST0247             1032              0       0.000000
ST0248             1032              0       0.000000
ST0249             1379              0       0.000000
ST0250             1379              0       0.000000
ST0251             1379              0       0.000000
ST0252             1379              0       0.000000
ST0253             1361              0       0.000000
ST0254             1032              0       0.000000
ST0255             1003              0       0.000000
ST0256             1379              0       0.000000
ST0257             1379              0       0.000000
ST0258             1379              0       0.000000
ST0259             1379              0       0.000000
ST0450             1379              0       0.000000
ST0435             1379              0       0.000000
ST0262             1379              0       0.000000
ST0263             1003              0       0.000000
ST0264              992              0       0.000000
ST0265             1379              0       0.000000
ST0266             1379              0       0.000000
ST0267             1379              0       0.000000
ST0268             1204              0       0.000000
ST0436             1379              0       0.000000
ST0270             1379              0       0.000000
ST0271             1379              0       0.000000
ST0272             1379              0       0.000000
ST0273             1326              0       0.000000
ST0274             1379              0       0.000000
ST0437             1379              0       0.000000
ST0276             1379              0       0.000000
ST0277             1379              0       0.000000
ST0438             1379              0       0.000000
ST0279             1379              0       0.000000
ST0280             1379              0       0.000000
ST0281             1379              0       0.000000
ST0282             1379              0       0.000000
ST0283             1379              0       0.000000
ST0284             1379              0       0.000000
ST0285              994              0       0.000000
ST0286             1379              0       0.000000
ST0287             1379              0       0.000000
ST0288             1379              0       0.000000
ST0289             1379              0       0.000000
ST0290              982              0       0.000000
ST0291             1360              0       0.000000
ST0439             1378              0       0.000000
ST0293             1379              0       0.000000
ST0294             1379              0       0.000000
ST0295             1379              0       0.000000
ST0296             1378              0       0.000000
ST0440             1379              0       0.000000
ST0298             1379              0       0.000000
ST0299             1379              0       0.000000
ST0300             1379              0       0.000000
ST0301             1379              0       0.000000
ST0302             1379              0       0.000000
ST0303             1379              0       0.000000
ST0304             1354              0       0.000000
ST0305             1379              0       0.000000
ST0306             1379              0       0.000000
ST0307             1379              0       0.000000
ST0308             1379              0       0.000000
ST0309             1379              0       0.000000
ST0310             1379              0       0.000000
ST0311             1379              0       0.000000
ST0312             1379              0       0.000000
ST0441             1379              0       0.000000
ST0314             1379              0       0.000000
ST0315             1379              0       0.000000
ST0316             1044              0       0.000000
ST0317             1379              0       0.000000
ST0318             1379              0       0.000000
ST0319             1379              0       0.000000
ST0320             1379              0       0.000000
ST0442             1003              0       0.000000
ST0322             1379              0       0.000000
ST0323             1379              0       0.000000
ST0324             1379              0       0.000000
ST0325              992              0       0.000000
ST0443             1379              0       0.000000
ST0327             1376              0       0.000000
ST0328             1379              0       0.000000
ST0329             1379              0       0.000000
ST0330              986              0       0.000000
ST0331             1379              0       0.000000
ST0332             1379              0       0.000000
ST0444             1379              0       0.000000
ST0334             1379              0       0.000000
ST0335             1379              0       0.000000
ST0336             1379              0       0.000000
ST0337             1379              0       0.000000
ST0338             1379              0       0.000000
ST0339             1379              0       0.000000
ST0340             1379              0       0.000000
ST0341              989              0       0.000000
ST0342             1379              0       0.000000
ST0343             1379              0       0.000000
ST0344             1379              0       0.000000
ST0345             1379              0       0.000000
ST0346             1360              0       0.000000
ST0445              991              0       0.000000
ST0348             1379              0       0.000000
ST0349             1379              0       0.000000
ST0350             1379              0       0.000000
ST0351             1379              0       0.000000
ST0352             1032              0       0.000000
ST0353             1379              0       0.000000
ST0354             1379              0       0.000000
ST0355             1379              0       0.000000
ST0356             1327              0       0.000000
ST0357             1379              0       0.000000
ST0446             1379              0       0.000000
ST0359             1379              0       0.000000
ST0360             1370              0       0.000000
ST0361             1379              0       0.000000
ST0362             1379              0       0.000000
ST0363             1379              0       0.000000
ST0364             1373              0       0.000000
ST0365             1379              0       0.000000
ST0366             1379              0       0.000000
ST0367             1379              0       0.000000
ST0368             1379              0       0.000000
ST0369             1379              0       0.000000

In [18]:
# 조석 주기성 후보 관측소 9개만 별도로 학습시키기

# 조석 주기성 후보
tidal_stations = [
    'ST0110', 'ST0326', 'ST0159',
    'ST0358', 'ST0347', 'ST0415',
    'ST0292', 'ST0313', 'ST0234'
]

# Train 분리
tidal_train = train.loc[train['station_id'].isin(tidal_stations)].copy()
normal_train = train.loc[~train['station_id'].isin(tidal_stations)].copy()

# Validation 분리
tidal_val = val.loc[val['station_id'].isin(tidal_stations)].copy()
normal_val = val.loc[~val['station_id'].isin(tidal_stations)].copy()

# 분리 결과 확인
print(f"Train : {len(train):,}")
print(f"  Tidal  : {len(tidal_train):,}")
print(f"  Normal : {len(normal_train):,}")

print(f"\nValidation : {len(val):,}")
print(f"  Tidal  : {len(tidal_val):,}")
print(f"  Normal : {len(normal_val):,}")

Train : 616,293
  Tidal  : 11,685
  Normal : 604,608

Validation : 133,316
  Tidal  : 2,566
  Normal : 130,750

In [22]:
# ============================================================
# 조석 후보 9개 관측소 별도 CatBoost 회귀모델
# ============================================================

# 1. 독립변수, 종속변수 분리
X_tidal_train = tidal_train[num_cols_fe + ['station_id']].copy()
X_tidal_val = tidal_val[num_cols_fe + ['station_id']].copy()

y_tidal_train = tidal_train['target_maxrise_6h']
y_tidal_val = tidal_val['target_maxrise_6h']

# 2. CatBoost 전용 범주형 변수 처리
X_tidal_train['station_id'] = X_tidal_train['station_id'].astype(str)
X_tidal_val['station_id'] = X_tidal_val['station_id'].astype(str)

# 3. 모델 정의
model_tidal = CatBoostRegressor(
    random_state=42,
    iterations=3000,
    cat_features=['station_id']
)

# 4. 모델 학습
model_tidal.fit(
    X_tidal_train,
    y_tidal_train,
    early_stopping_rounds=100,
    eval_set=(X_tidal_val, y_tidal_val),
    verbose=200
)

# 5. 예측
pred_tidal_val = model_tidal.predict(X_tidal_val)
pred_tidal_train = model_tidal.predict(X_tidal_train)

# 6. 학습 결과 확인
print('Best iteration:', model_tidal.best_iteration_)
print('Tree count:', model_tidal.tree_count_)
print('Best score:', model_tidal.best_score_['validation']['RMSE'])
print()

# 7. RMSE 계산
rmse_tidal_val = root_mean_squared_error(
    y_tidal_val, pred_tidal_val
)

rmse_tidal_train = root_mean_squared_error(
    y_tidal_train, pred_tidal_train
)

print('val RMSE: ', rmse_tidal_val)
print('train RMSE: ', rmse_tidal_train)
print('Gap: ', rmse_tidal_val - rmse_tidal_train)

Learning rate set to 0.038324
0:	learn: 1.7155655	test: 1.6789126	best: 1.6789126 (0)	total: 173ms	remaining: 8m 38s
200:	learn: 0.4074975	test: 0.4301416	best: 0.4301416 (200)	total: 8.73s	remaining: 2m 1s
400:	learn: 0.3449974	test: 0.3856054	best: 0.3856054 (400)	total: 17.1s	remaining: 1m 50s
600:	learn: 0.3077946	test: 0.3683486	best: 0.3683486 (600)	total: 25.7s	remaining: 1m 42s
800:	learn: 0.2828673	test: 0.3595638	best: 0.3595105 (799)	total: 33.9s	remaining: 1m 33s
1000:	learn: 0.2631933	test: 0.3543644	best: 0.3543644 (1000)	total: 42s	remaining: 1m 23s
1200:	learn: 0.2471664	test: 0.3504691	best: 0.3504691 (1200)	total: 50.2s	remaining: 1m 15s
1400:	learn: 0.2333971	test: 0.3487546	best: 0.3486535 (1395)	total: 58.3s	remaining: 1m 6s
1600:	learn: 0.2214358	test: 0.3474502	best: 0.3473743 (1592)	total: 1m 6s	remaining: 58.2s
1800:	learn: 0.2109443	test: 0.3464440	best: 0.3463395 (1794)	total: 1m 15s	remaining: 50s
2000:	learn: 0.2017917	test: 0.3456331	best: 0.3456080 (1997)	total: 1m 23s	remaining: 41.7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.3455126273
bestIteration = 2010

Shrink model to first 2011 iterations.
Best iteration: 2010
Tree count: 2011
Best score: 0.3455126273400033

val RMSE:  0.3455126289634656
train RMSE:  0.20205660474029127
Gap:  0.1434560242231743

In [24]:
# 1. 기존 통합모델 독립변수 및 종속변수 정의
X_train_with_station = train[num_cols_fe + ['station_id']].copy()
X_val_with_station = val[num_cols_fe + ['station_id']].copy()

y_train = train['target_maxrise_6h']
y_val = val['target_maxrise_6h']

X_train_with_station['station_id'] = X_train_with_station['station_id'].astype(str)
X_val_with_station['station_id'] = X_val_with_station['station_id'].astype(str)

# 2. 기존 통합모델 정의
model_base_no_ohe = CatBoostRegressor(
    random_state=42,
    iterations=3000,
    cat_features=['station_id']
)

# 3. 모델 학습
model_base_no_ohe.fit(
    X_train_with_station,
    y_train,
    early_stopping_rounds=100,
    eval_set=(X_val_with_station, y_val),
    verbose=200
)

# 4. 기존 통합모델로 Tidal Validation 예측
pred_tidal_val_base = model_base_no_ohe.predict(X_tidal_val)

# 5. RMSE 비교
rmse_tidal_val_base = root_mean_squared_error(
    y_tidal_val, pred_tidal_val_base
)

print('기존 통합모델 Tidal RMSE:', rmse_tidal_val_base)
print('별도 Tidal 모델 RMSE:', rmse_tidal_val)
print('RMSE 변화:', rmse_tidal_val - rmse_tidal_val_base)

Learning rate set to 0.071425
0:	learn: 0.3895386	test: 0.3444227	best: 0.3444227 (0)	total: 169ms	remaining: 8m 26s
200:	learn: 0.2300278	test: 0.2035631	best: 0.2035631 (200)	total: 32.7s	remaining: 7m 35s
400:	learn: 0.2182347	test: 0.1979222	best: 0.1979222 (400)	total: 1m 6s	remaining: 7m 11s
600:	learn: 0.2110872	test: 0.1958141	best: 0.1958141 (600)	total: 1m 38s	remaining: 6m 31s
800:	learn: 0.2055799	test: 0.1947004	best: 0.1947004 (800)	total: 2m 12s	remaining: 6m 3s
1000:	learn: 0.2011655	test: 0.1941687	best: 0.1941687 (1000)	total: 2m 43s	remaining: 5m 27s
1200:	learn: 0.1974401	test: 0.1937451	best: 0.1937451 (1200)	total: 3m 15s	remaining: 4m 52s
1400:	learn: 0.1941079	test: 0.1933177	best: 0.1932767 (1372)	total: 3m 47s	remaining: 4m 19s
1600:	learn: 0.1913972	test: 0.1931965	best: 0.1931434 (1536)	total: 4m 19s	remaining: 3m 47s
1800:	learn: 0.1888074	test: 0.1930250	best: 0.1929570 (1778)	total: 4m 52s	remaining: 3m 14s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.1929570043
bestIteration = 1778

Shrink model to first 1779 iterations.
기존 통합모델 Tidal RMSE: 0.3869514374893429
별도 Tidal 모델 RMSE: 0.3455126289634656
RMSE 변화: -0.041438808525877335

In [25]:
# ============================================================
# Normal 관측소 전용 CatBoost 회귀모델
# ============================================================

# 1. 독립변수, 종속변수 분리
X_normal_train = normal_train[num_cols_fe + ['station_id']].copy()
X_normal_val = normal_val[num_cols_fe + ['station_id']].copy()

y_normal_train = normal_train['target_maxrise_6h']
y_normal_val = normal_val['target_maxrise_6h']

# 2. CatBoost 전용 범주형 변수 처리
X_normal_train['station_id'] = X_normal_train['station_id'].astype(str)
X_normal_val['station_id'] = X_normal_val['station_id'].astype(str)

# 3. 모델 정의
model_normal = CatBoostRegressor(
    random_state=42,
    iterations=3000,
    cat_features=['station_id']
)

# 4. 모델 학습
model_normal.fit(
    X_normal_train,
    y_normal_train,
    early_stopping_rounds=100,
    eval_set=(X_normal_val, y_normal_val),
    verbose=200
)

# 5. 예측
pred_normal_val = model_normal.predict(X_normal_val)
pred_normal_train = model_normal.predict(X_normal_train)

# 6. 학습 결과 확인
print('Best iteration:', model_normal.best_iteration_)
print('Tree count:', model_normal.tree_count_)
print('Best score:', model_normal.best_score_['validation']['RMSE'])
print()

# 7. RMSE 계산
rmse_normal_val = root_mean_squared_error(
    y_normal_val, pred_normal_val
)

rmse_normal_train = root_mean_squared_error(
    y_normal_train, pred_normal_train
)

print('val RMSE: ', rmse_normal_val)
print('train RMSE: ', rmse_normal_train)
print('Gap: ', rmse_normal_val - rmse_normal_train)

Learning rate set to 0.07121
0:	learn: 0.2846285	test: 0.2243682	best: 0.2243682 (0)	total: 242ms	remaining: 12m 6s
200:	learn: 0.2179375	test: 0.1896694	best: 0.1896694 (200)	total: 34.2s	remaining: 7m 56s
400:	learn: 0.2078211	test: 0.1870848	best: 0.1870649 (399)	total: 1m 6s	remaining: 7m 9s
600:	learn: 0.2017569	test: 0.1867552	best: 0.1867185 (590)	total: 1m 43s	remaining: 6m 53s
800:	learn: 0.1969781	test: 0.1866371	best: 0.1865962 (742)	total: 2m 23s	remaining: 6m 34s
1000:	learn: 0.1929121	test: 0.1864860	best: 0.1864503 (952)	total: 2m 56s	remaining: 5m 51s
1200:	learn: 0.1895492	test: 0.1862929	best: 0.1862671 (1196)	total: 3m 27s	remaining: 5m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.186251702
bestIteration = 1211

Shrink model to first 1212 iterations.
Best iteration: 1211
Tree count: 1212
Best score: 0.18625170199354416

val RMSE:  0.1862517019446085
train RMSE:  0.18867773787758255
Gap:  -0.002426035932974052

In [27]:
# ============================================================
# Tidal + Normal 예측값 결합 및 전체 Validation RMSE
# ============================================================

# 1. 두 모델의 예측값 결합 (기존 인덱스 유지)
pred_val_split = pd.Series(index=val.index, dtype=float)

pred_val_split.loc[tidal_val.index] = pred_tidal_val
pred_val_split.loc[normal_val.index] = pred_normal_val

# 2. 전체 Validation RMSE 계산
rmse_val_split = root_mean_squared_error(
    val['target_maxrise_6h'],
    pred_val_split
)

print(f'분리모델 전체 Validation RMSE: {rmse_val_split:.6f}')

분리모델 전체 Validation RMSE: 0.190577